In [1]:
import pandas as pd
import numpy as np
import yaml

In [2]:
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

# Contamination dataframes

## AIR

### Air facilities > df1

In [3]:
df_air_releases_facilities = pd.read_csv(config['data']['raw']['file1'])
display(df_air_releases_facilities.head())
display(df_air_releases_facilities.dtypes)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason
0,2026/02/13,Germany,2013,1.0,Energy sector,1(e),https://registry.gdi-de.org/id/de.nw.inspire.p...,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,50.986950,NaN,AIR,Sulphur oxides (SOX),824000.0,NaN
1,2026/02/13,Sweden,2020,7.0,Intensive livestock production and aquaculture,7(a)(i),SE.CAED/10017896.Facility,Skåneägg Produktion AB,MÖRARP,12.849550,56.053160,NaN,AIR,Ammonia (NH3),16300.0,NaN
2,2026/02/13,Romania,2013,5.0,Waste and wastewater management,5(d),RO.CAED/104TL0001.FACILITY,SC ECOREC SA,TULCEA,28.769671,45.190459,NaN,AIR,Methane (CH4),269000.0,NaN
3,2026/02/13,Italy,2021,7.0,Intensive livestock production and aquaculture,7(a),IT.CAED/370602036.FACILITY,RONCHETRIN 1,GAZZO VERONESE,11.106667,45.123611,NaN,AIR,Ammonia (NH3),31920.0,NaN
4,2026/02/13,Czechia,2007,1.0,Energy sector,1(c),CZ.MZP.U423/CZ14819275.FACILITY,energetika,Štětí,14.380370,50.462296,NaN,AIR,Sulphur oxides (SOX),507000.0,NaN

PublicationDate                  object
countryName                      object
reportingYear                     int64
EPRTR_SectorCode                float64
EPRTR_SectorName                 object
EPRTRAnnexIMainActivity          object
FacilityInspireId                object
facilityName                     object
city                             object
Longitude                       float64
Latitude                        float64
addressConfidentialityReason     object
TargetRelease                    object
Pollutant                        object
Releases                        float64
confidentialityReason            object
dtype: object

In [4]:
df_air_releases_facilities.PublicationDate.unique()

array(['2026/02/13'], dtype=object)

In [5]:
df_air_releases_facilities = df_air_releases_facilities.drop(columns=['PublicationDate', 'EPRTR_SectorCode', 'EPRTRAnnexIMainActivity', 'FacilityInspireId', 'addressConfidentialityReason', 'confidentialityReason'])

In [6]:
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df1 = rename_columns(df_air_releases_facilities)

In [7]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    #print("\n    ---- df info ---")
    #print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df1)

    ----- Shape -----
(372206, 10)

    ---- Empty Values ---
countryname            0
reportingyear          0
eprtr_sectorname    4985
facilityname           1
city                 133
longitude            806
latitude             806
targetrelease          0
pollutant              0
releases              78
dtype: int64

    ----- Dtypes -----
countryname          object
reportingyear         int64
eprtr_sectorname     object
facilityname         object
city                 object
longitude           float64
latitude            float64
targetrelease        object
pollutant            object
releases            float64
dtype: object

In [9]:
df1.dropna(inplace=True)
print(df1.shape)

(366206, 10)

In [10]:
df1.head()

,countryname,reportingyear,eprtr_sectorname,facilityname,city,longitude,latitude,targetrelease,pollutant,releases
0,Germany,2013,Energy sector,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,50.986950,AIR,Sulphur oxides (SOX),824000.0
1,Sweden,2020,Intensive livestock production and aquaculture,Skåneägg Produktion AB,MÖRARP,12.849550,56.053160,AIR,Ammonia (NH3),16300.0
2,Romania,2013,Waste and wastewater management,SC ECOREC SA,TULCEA,28.769671,45.190459,AIR,Methane (CH4),269000.0
3,Italy,2021,Intensive livestock production and aquaculture,RONCHETRIN 1,GAZZO VERONESE,11.106667,45.123611,AIR,Ammonia (NH3),31920.0
4,Czechia,2007,Energy sector,energetika,Štětí,14.380370,50.462296,AIR,Sulphur oxides (SOX),507000.0

In [32]:
df1.isnull().sum()

countryname         0
reportingyear       0
eprtr_sectorname    0
facilityname        0
city                0
longitude           0
latitude            0
targetrelease       0
pollutant           0
releases            0
dtype: int64

### Air releases national > df2

In [11]:
df_air_releases_national = pd.read_csv(config['data']['raw']['file3'])
display(df_air_releases_national.head())
display(df_air_releases_national.dtypes)
display(df_air_releases_national.shape)

,PublicationDate,countryName,reportingYear,Pollutant,Releases
0,2026/02/13,France,2023,Tetrachloroethylene,1.108000e+04
1,2026/02/13,Poland,2012,Methane (CH4),4.971020e+08
2,2026/02/13,Czechia,2013,Methane (CH4),1.865000e+06
3,2026/02/13,Portugal,2024,Pentachlorobenzene,1.070000e+00
4,2026/02/13,Bulgaria,2009,Non-methane volatile organic compounds (NMVOC),3.964000e+06

PublicationDate     object
countryName         object
reportingYear        int64
Pollutant           object
Releases           float64
dtype: object

(13639, 5)

In [12]:
df_air_releases_national = df_air_releases_national.drop(columns=['PublicationDate'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df2 = rename_columns(df_air_releases_national)

df2.dropna(inplace=True)
print(df2.shape)

(13639, 4)

In [13]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df2)

    ----- Shape -----
(13639, 4)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13639 entries, 0 to 13638
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   countryname    13639 non-null  object
 1   reportingyear  13639 non-null  int64
 2   pollutant      13639 non-null  object
 3   releases       13639 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 426.3+ KB
None

    ---- Empty Values ---
countryname      0
reportingyear    0
pollutant        0
releases         0
dtype: int64

    ----- Dtypes -----
countryname       object
reportingyear      int64
pollutant         object
releases         float64
dtype: object

### Air releases sector > df3

In [14]:
df_air_releases_sector = pd.read_csv(config['data']['raw']['file4'])
display(df_air_releases_sector.head())
display(df_air_releases_sector.dtypes)
display(df_air_releases_sector.shape)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,Pollutant,Releases
0,2026/02/13,Norway,2013,3.0,Mineral industry,Mercury and compounds (as Hg),2.500000e+01
1,2026/02/13,Czechia,2014,1.0,Energy sector,Arsenic and compounds (as As),1.363400e+03
2,2026/02/13,Italy,2008,1.0,Energy sector,Nitrogen oxides (NOX),1.039530e+08
3,2026/02/13,Spain,2018,1.0,Energy sector,Carbon dioxide (CO2),7.229500e+10
4,2026/02/13,Serbia,2022,1.0,Energy sector,Sulphur oxides (SOX),3.087640e+08

PublicationDate      object
countryName          object
reportingYear         int64
EPRTR_SectorCode    float64
EPRTR_SectorName     object
Pollutant            object
Releases            float64
dtype: object

(42000, 7)

In [15]:
df_air_releases_sector = df_air_releases_sector.drop(columns=['PublicationDate'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df3 = rename_columns(df_air_releases_national)

df3.dropna(inplace=True)
print(df3.shape)

(13639, 4)

In [16]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df3)

    ----- Shape -----
(13639, 4)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13639 entries, 0 to 13638
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   countryname    13639 non-null  object
 1   reportingyear  13639 non-null  int64
 2   pollutant      13639 non-null  object
 3   releases       13639 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 426.3+ KB
None

    ---- Empty Values ---
countryname      0
reportingyear    0
pollutant        0
releases         0
dtype: int64

    ----- Dtypes -----
countryname       object
reportingyear      int64
pollutant         object
releases         float64
dtype: object

## WATER

### Water facilities > df4

In [17]:
df_water_releases_facilities = pd.read_csv(config['data']['raw']['file2'])
display(df_water_releases_facilities.head())
display(df_water_releases_facilities.dtypes)

C:\Users\fotos\AppData\Local\Temp\ipykernel_10428\3054174240.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_water_releases_facilities = pd.read_csv(config['data']['raw']['file2'])

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason
0,2026/02/13,United Kingdom,2014,1.0,Energy sector,1(c),UK.CAED/BEISOffsh-Forties-Alpha.FACILITY,Forties Alpha,--,0.582170,57.435510,NaN,WATER,Anthracene,12.10,NaN
1,2026/02/13,Germany,2011,4.0,Chemical industry,4(b)(iv),https://registry.gdi-de.org/id/de.nw.inspire.p...,Solvay GmbH,Rheinberg,6.577830,51.564710,NaN,WATER,Cadmium and compounds (as Cd),113.00,NaN
2,2026/02/13,Germany,2022,5.0,Waste and wastewater management,5(f),https://registry.gdi-de.org/id/de.by.inspire.p...,AmperVerband,Olching,11.360499,48.233805,NaN,WATER,Total organic carbon(as total C or COD/3) (TOC),77700.00,NaN
3,2026/02/13,Hungary,2007,5.0,Waste and wastewater management,5(f),HU.OKIR/100609995.FACILITY,Fővárosi Csatornázási Művek Zrt.,Budapest 04. ker.,19.073994,47.572780,NaN,WATER,Mercury and compounds (as Hg),5.05,NaN
4,2026/02/13,Portugal,2014,1.0,Energy sector,1(a),PT.CAED/PT.APA05769662.CI,Refinaria de Sines (CI),SINES,-8.800138,37.963901,NaN,WATER,Total organic carbon(as total C or COD/3) (TOC),62100.00,NaN

PublicationDate                  object
countryName                      object
reportingYear                     int64
EPRTR_SectorCode                float64
EPRTR_SectorName                 object
EPRTRAnnexIMainActivity          object
FacilityInspireId                object
facilityName                     object
city                             object
Longitude                       float64
Latitude                        float64
addressConfidentialityReason     object
TargetRelease                    object
Pollutant                        object
Releases                        float64
confidentialityReason            object
dtype: object

In [21]:
df_water_releases_facilities = df_water_releases_facilities.drop(columns=['PublicationDate', 'EPRTR_SectorCode', 'EPRTRAnnexIMainActivity', 'FacilityInspireId', 'addressConfidentialityReason', 'confidentialityReason'])

In [22]:
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df4 = rename_columns(df_water_releases_facilities)

df4.dropna(inplace=True)
print(df4.shape)

(251384, 10)

In [23]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df4)

    ----- Shape -----
(251384, 10)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
Index: 251384 entries, 0 to 254155
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   countryname       251384 non-null  object
 1   reportingyear     251384 non-null  int64
 2   eprtr_sectorname  251384 non-null  object
 3   facilityname      251384 non-null  object
 4   city              251384 non-null  object
 5   longitude         251384 non-null  float64
 6   latitude          251384 non-null  float64
 7   targetrelease     251384 non-null  object
 8   pollutant         251384 non-null  object
 9   releases          251384 non-null  float64
dtypes: float64(3), int64(1), object(6)
memory usage: 21.1+ MB
None

    ---- Empty Values ---
countryname         0
reportingyear       0
eprtr_sectorname    0
facilityname        0
city                0
longitude           0
latitude            0
targetrelease       0
pollutant           0
releases            0
dtype: int64

    ----- Dtypes -----
countryname          object
reportingyear         int64
eprtr_sectorname     object
facilityname         object
city                 object
longitude           float64
latitude            float64
targetrelease        object
pollutant            object
releases            float64
dtype: object

In [24]:
df4.head()

,countryname,reportingyear,eprtr_sectorname,facilityname,city,longitude,latitude,targetrelease,pollutant,releases
0,United Kingdom,2014,Energy sector,Forties Alpha,--,0.582170,57.435510,WATER,Anthracene,12.10
1,Germany,2011,Chemical industry,Solvay GmbH,Rheinberg,6.577830,51.564710,WATER,Cadmium and compounds (as Cd),113.00
2,Germany,2022,Waste and wastewater management,AmperVerband,Olching,11.360499,48.233805,WATER,Total organic carbon(as total C or COD/3) (TOC),77700.00
3,Hungary,2007,Waste and wastewater management,Fővárosi Csatornázási Művek Zrt.,Budapest 04. ker.,19.073994,47.572780,WATER,Mercury and compounds (as Hg),5.05
4,Portugal,2014,Energy sector,Refinaria de Sines (CI),SINES,-8.800138,37.963901,WATER,Total organic carbon(as total C or COD/3) (TOC),62100.00

In [31]:
df4.isnull().sum()

countryname         0
reportingyear       0
eprtr_sectorname    0
facilityname        0
city                0
longitude           0
latitude            0
targetrelease       0
pollutant           0
releases            0
dtype: int64

### Water releases national > df5

In [25]:
df_water_releases_national = pd.read_csv(config['data']['raw']['file5'])
display(df_water_releases_national.head())
display(df_water_releases_national.dtypes)
display(df_water_releases_national.shape)

,PublicationDate,countryName,reportingYear,Pollutant,Releases
0,2026/02/13,Italy,2019,Total nitrogen,24776324.60
1,2026/02/13,Belgium,2018,Fluoranthene,3.08
2,2026/02/13,Finland,2013,Phenols (as total C),544.20
3,2026/02/13,Germany,2020,Isoproturon,30.80
4,2026/02/13,Germany,2010,Total phosphorus,1856310.00

PublicationDate     object
countryName         object
reportingYear        int64
Pollutant           object
Releases           float64
dtype: object

(12607, 5)

In [26]:
df_water_releases_national = df_water_releases_national.drop(columns=['PublicationDate'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df5 = rename_columns(df_water_releases_national)

df5.dropna(inplace=True)
print(df5.shape)

(12607, 4)

In [27]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df5)

    ----- Shape -----
(12607, 4)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12607 entries, 0 to 12606
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   countryname    12607 non-null  object
 1   reportingyear  12607 non-null  int64
 2   pollutant      12607 non-null  object
 3   releases       12607 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 394.1+ KB
None

    ---- Empty Values ---
countryname      0
reportingyear    0
pollutant        0
releases         0
dtype: int64

    ----- Dtypes -----
countryname       object
reportingyear      int64
pollutant         object
releases         float64
dtype: object

### Water releases sector > df6

In [28]:
df_water_releases_sector = pd.read_csv(config['data']['raw']['file6'])
display(df_water_releases_sector.head())
display(df_water_releases_sector.dtypes)
display(df_water_releases_sector.shape)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,Pollutant,Releases
0,2026/02/13,Germany,2024,2.0,Production and processing of metals,Zinc and compounds (as Zn),11370.0
1,2026/02/13,Germany,2013,5.0,Waste and wastewater management,Total nitrogen,38222100.0
2,2026/02/13,Netherlands,2024,5.0,Waste and wastewater management,Cyanides (as total CN),655.0
3,2026/02/13,Sweden,2016,6.0,Paper and wood production and processing,Total nitrogen,1728800.0
4,2026/02/13,Italy,2007,6.0,Paper and wood production and processing,Chromium and compounds (as Cr),452.2

PublicationDate      object
countryName          object
reportingYear         int64
EPRTR_SectorCode    float64
EPRTR_SectorName     object
Pollutant            object
Releases            float64
dtype: object

(33132, 7)

In [29]:
df_water_releases_sector = df_water_releases_sector.drop(columns=['PublicationDate'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df6 = rename_columns(df_water_releases_sector)

df6.dropna(inplace=True)
print(df6.shape)

(32227, 6)

In [30]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df6)

    ----- Shape -----
(32227, 6)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
Index: 32227 entries, 0 to 33131
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   countryname       32227 non-null  object
 1   reportingyear     32227 non-null  int64
 2   eprtr_sectorcode  32227 non-null  float64
 3   eprtr_sectorname  32227 non-null  object
 4   pollutant         32227 non-null  object
 5   releases          32227 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.7+ MB
None

    ---- Empty Values ---
countryname         0
reportingyear       0
eprtr_sectorcode    0
eprtr_sectorname    0
pollutant           0
releases            0
dtype: int64

    ----- Dtypes -----
countryname          object
reportingyear         int64
eprtr_sectorcode    float64
eprtr_sectorname     object
pollutant            object
releases            float64
dtype: object

# NUTS - facilities df

In [33]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

## NUTS Water -> df1_NUTS

In [39]:
df1_NUTS = df1.dropna(subset=['longitude', 'latitude']).copy()

In [41]:
geometry = [Point(xy) for xy in zip(df1_NUTS['longitude'], df1_NUTS['latitude'])]
gdf_puntos = gpd.GeoDataFrame(df1_NUTS, geometry=geometry, crs="EPSG:4326")

In [42]:
url_nuts = "https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_10M_2024_4326.geojson"
gdf_nuts = gpd.read_file(url_nuts)

In [43]:
gdf_nuts_2 = gdf_nuts[gdf_nuts['LEVL_CODE'] == 2]

In [44]:
df1_NUTS = gpd.sjoin(gdf_puntos, gdf_nuts_2, how="left", predicate="within")

In [45]:
df1_NUTS = pd.DataFrame(df1_NUTS).drop(columns=['geometry', 'index_right'])

In [47]:
df1_NUTS.head()

,countryname,reportingyear,eprtr_sectorname,facilityname,city,longitude,latitude,targetrelease,pollutant,releases,...,COAST_TYPE,NAME_ENGL,NAME_FREN,ISO3_CODE,SVRG_UN,CAPT,EU_STAT,EFTA_STAT,CC_STAT,NAME_GERM
0,Germany,2013,Energy sector,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,50.986950,AIR,Sulphur oxides (SOX),824000.0,...,NaN,Germany,Allemagne,DEU,UN Member State,Berlin,T,F,F,Deutschland
1,Sweden,2020,Intensive livestock production and aquaculture,Skåneägg Produktion AB,MÖRARP,12.849550,56.053160,AIR,Ammonia (NH3),16300.0,...,NaN,Sweden,Suède,SWE,UN Member State,Stockholm,T,F,F,Schweden
2,Romania,2013,Waste and wastewater management,SC ECOREC SA,TULCEA,28.769671,45.190459,AIR,Methane (CH4),269000.0,...,NaN,Romania,Roumanie,ROU,UN Member State,Bucharest,T,F,F,Rumänien
3,Italy,2021,Intensive livestock production and aquaculture,RONCHETRIN 1,GAZZO VERONESE,11.106667,45.123611,AIR,Ammonia (NH3),31920.0,...,NaN,Italy,Italie,ITA,UN Member State,Rome,T,F,F,Italien
4,Czechia,2007,Energy sector,energetika,Štětí,14.380370,50.462296,AIR,Sulphur oxides (SOX),507000.0,...,NaN,Czechia,Tchéquie,CZE,UN Member State,Prague,T,F,F,Tschechien

In [48]:
df1_NUTS.dtypes

countryname          object
reportingyear         int64
eprtr_sectorname     object
facilityname         object
city                 object
longitude           float64
latitude            float64
targetrelease        object
pollutant            object
releases            float64
NUTS_ID              object
LEVL_CODE           float64
CNTR_CODE            object
NAME_LATN            object
NUTS_NAME            object
MOUNT_TYPE          float64
URBN_TYPE           float64
COAST_TYPE          float64
NAME_ENGL            object
NAME_FREN            object
ISO3_CODE            object
SVRG_UN              object
CAPT                 object
EU_STAT              object
EFTA_STAT            object
CC_STAT              object
NAME_GERM            object
dtype: object

In [71]:
df1_NUTS_clean = df1_NUTS.drop(columns=['NAME_LATN', 'NAME_ENGL', 'NAME_FREN', 'SVRG_UN', 'CAPT', 'EU_STAT', 'EU_STAT', 'CC_STAT', 'NAME_GERM', 'MOUNT_TYPE', 'URBN_TYPE', 'COAST_TYPE', 'EFTA_STAT', 'LEVL_CODE'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df1_NUTS_clean = rename_columns(df1_NUTS_clean)

In [73]:
df1_NUTS_clean['releases'] = df1_NUTS_clean['releases'].astype(int)
df1_NUTS_clean.head()

,countryname,reportingyear,eprtr_sectorname,facilityname,city,longitude,latitude,targetrelease,pollutant,releases,nuts_id,cntr_code,nuts_name,iso3_code
0,Germany,2013,Energy sector,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,50.986950,AIR,Sulphur oxides (SOX),824000,DEA2,DE,Köln,DEU
1,Sweden,2020,Intensive livestock production and aquaculture,Skåneägg Produktion AB,MÖRARP,12.849550,56.053160,AIR,Ammonia (NH3),16300,SE22,SE,Sydsverige,SWE
2,Romania,2013,Waste and wastewater management,SC ECOREC SA,TULCEA,28.769671,45.190459,AIR,Methane (CH4),269000,RO22,RO,Sud-Est,ROU
3,Italy,2021,Intensive livestock production and aquaculture,RONCHETRIN 1,GAZZO VERONESE,11.106667,45.123611,AIR,Ammonia (NH3),31920,ITH3,IT,Veneto,ITA
4,Czechia,2007,Energy sector,energetika,Štětí,14.380370,50.462296,AIR,Sulphur oxides (SOX),507000,CZ04,CZ,Severozápad,CZE

## NUTS Air -> df4_NUTS

In [58]:
df4_NUTS = df4.dropna(subset=['longitude', 'latitude']) . copy()

geometry = [Point(xy) for xy in zip(df4_NUTS['longitude' ], df4_NUTS['latitude' ])]
gdf_puntos = gpd.GeoDataFrame(df4_NUTS, geometry=geometry, crs="EPSG:4326")

url_nuts = "https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_10M_2024_4326.geojson"
gdf_nuts = gpd.read_file(url_nuts)

gdf_nuts_2 = gdf_nuts[gdf_nuts['LEVL_CODE' ] == 2]

df4_NUTS = gpd.sjoin(gdf_puntos, gdf_nuts_2, how="left", predicate="within")

df4_NUTS = pd.DataFrame(df4_NUTS).drop(columns=['geometry', 'index_right'])

In [74]:
df4_NUTS_clean = df4_NUTS.drop(columns=['NAME_LATN', 'NAME_ENGL', 'NAME_FREN', 'SVRG_UN', 'CAPT', 'EU_STAT', 'EU_STAT', 'CC_STAT', 'NAME_GERM', 'MOUNT_TYPE', 'URBN_TYPE', 'COAST_TYPE', 'EFTA_STAT', 'LEVL_CODE'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df4_NUTS_clean = rename_columns(df4_NUTS_clean)

In [79]:
df4_NUTS_clean['releases'] = df4_NUTS_clean['releases'].astype(int)
df4_NUTS_clean.head()

,countryname,reportingyear,eprtr_sectorname,facilityname,city,longitude,latitude,targetrelease,pollutant,releases,nuts_id,cntr_code,nuts_name,iso3_code
0,United Kingdom,2014,Energy sector,Forties Alpha,--,0.582170,57.435510,WATER,Anthracene,12,NaN,NaN,NaN,NaN
1,Germany,2011,Chemical industry,Solvay GmbH,Rheinberg,6.577830,51.564710,WATER,Cadmium and compounds (as Cd),113,DEA1,DE,Düsseldorf,DEU
2,Germany,2022,Waste and wastewater management,AmperVerband,Olching,11.360499,48.233805,WATER,Total organic carbon(as total C or COD/3) (TOC),77700,DE21,DE,Oberbayern,DEU
3,Hungary,2007,Waste and wastewater management,Fővárosi Csatornázási Művek Zrt.,Budapest 04. ker.,19.073994,47.572780,WATER,Mercury and compounds (as Hg),5,HU11,HU,Budapest,HUN
4,Portugal,2014,Energy sector,Refinaria de Sines (CI),SINES,-8.800138,37.963901,WATER,Total organic carbon(as total C or COD/3) (TOC),62100,PT1C,PT,Alentejo,PRT

In [80]:
df1_NUTS_clean.nuts_id.isna().value_counts()

nuts_id
False    321861
True      44345
Name: count, dtype: int64

In [81]:
df4_NUTS_clean.dtypes

countryname          object
reportingyear         int64
eprtr_sectorname     object
facilityname         object
city                 object
longitude           float64
latitude            float64
targetrelease        object
pollutant            object
releases              int64
nuts_id              object
cntr_code            object
nuts_name            object
iso3_code            object
dtype: object

In [78]:
df1_NUTS_clean.dtypes

countryname          object
reportingyear         int64
eprtr_sectorname     object
facilityname         object
city                 object
longitude           float64
latitude            float64
targetrelease        object
pollutant            object
releases              int64
nuts_id              object
cntr_code            object
nuts_name            object
iso3_code            object
dtype: object

 ## To .csv

In [82]:
df1_NUTS_clean.to_csv('air_nuts_clean.csv', index=False, encoding='utf-8')

In [83]:
df4_NUTS_clean.to_csv('water_nuts_clean.csv', index=False, encoding='utf-8')