In [1]:
import pandas as pd
import numpy as np
import yaml

In [2]:
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

# Contamination dataframes

## AIR

### Air facilities > df1

In [3]:
df_air_releases_facilities = pd.read_csv(config['data']['raw']['file1'])
display(df_air_releases_facilities.head())
display(df_air_releases_facilities.dtypes)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason
0,2026/02/13,Germany,2013,1.0,Energy sector,1(e),https://registry.gdi-de.org/id/de.nw.inspire.p...,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,50.986950,NaN,AIR,Sulphur oxides (SOX),824000.0,NaN
1,2026/02/13,Sweden,2020,7.0,Intensive livestock production and aquaculture,7(a)(i),SE.CAED/10017896.Facility,Skåneägg Produktion AB,MÖRARP,12.849550,56.053160,NaN,AIR,Ammonia (NH3),16300.0,NaN
2,2026/02/13,Romania,2013,5.0,Waste and wastewater management,5(d),RO.CAED/104TL0001.FACILITY,SC ECOREC SA,TULCEA,28.769671,45.190459,NaN,AIR,Methane (CH4),269000.0,NaN
3,2026/02/13,Italy,2021,7.0,Intensive livestock production and aquaculture,7(a),IT.CAED/370602036.FACILITY,RONCHETRIN 1,GAZZO VERONESE,11.106667,45.123611,NaN,AIR,Ammonia (NH3),31920.0,NaN
4,2026/02/13,Czechia,2007,1.0,Energy sector,1(c),CZ.MZP.U423/CZ14819275.FACILITY,energetika,Štětí,14.380370,50.462296,NaN,AIR,Sulphur oxides (SOX),507000.0,NaN

PublicationDate                  object
countryName                      object
reportingYear                     int64
EPRTR_SectorCode                float64
EPRTR_SectorName                 object
EPRTRAnnexIMainActivity          object
FacilityInspireId                object
facilityName                     object
city                             object
Longitude                       float64
Latitude                        float64
addressConfidentialityReason     object
TargetRelease                    object
Pollutant                        object
Releases                        float64
confidentialityReason            object
dtype: object

In [4]:
df_air_releases_facilities.PublicationDate.unique()

array(['2026/02/13'], dtype=object)

In [5]:
df_air_releases_facilities = df_air_releases_facilities.drop(columns=['PublicationDate'])

In [6]:
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df1 = rename_columns(df_air_releases_facilities)

In [7]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    #print("\n    ---- df info ---")
    #print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df1)

    ----- Shape -----
(372206, 15)

    ---- Empty Values ---
countryname                          0
reportingyear                        0
eprtr_sectorcode                  4985
eprtr_sectorname                  4985
eprtranneximainactivity           4985
facilityinspireid                    0
facilityname                         1
city                               133
longitude                          806
latitude                           806
addressconfidentialityreason    371400
targetrelease                        0
pollutant                            0
releases                            78
confidentialityreason           372128
dtype: int64

    ----- Dtypes -----
countryname                      object
reportingyear                     int64
eprtr_sectorcode                float64
eprtr_sectorname                 object
eprtranneximainactivity          object
facilityinspireid                object
facilityname                     object
city                             object
longitude                       float64
latitude                        float64
addressconfidentialityreason     object
targetrelease                    object
pollutant                        object
releases                        float64
confidentialityreason            object
dtype: object

In [8]:
df1.dropna(inplace=True)
print(df_air_releases_facilities.shape)

(0, 15)

### Air releases national > df2

In [9]:
df_air_releases_national = pd.read_csv(config['data']['raw']['file3'])
display(df_air_releases_national.head())
display(df_air_releases_national.dtypes)
display(df_air_releases_national.shape)

,PublicationDate,countryName,reportingYear,Pollutant,Releases
0,2026/02/13,France,2023,Tetrachloroethylene,1.108000e+04
1,2026/02/13,Poland,2012,Methane (CH4),4.971020e+08
2,2026/02/13,Czechia,2013,Methane (CH4),1.865000e+06
3,2026/02/13,Portugal,2024,Pentachlorobenzene,1.070000e+00
4,2026/02/13,Bulgaria,2009,Non-methane volatile organic compounds (NMVOC),3.964000e+06

PublicationDate     object
countryName         object
reportingYear        int64
Pollutant           object
Releases           float64
dtype: object

(13639, 5)

In [10]:
df_air_releases_national = df_air_releases_national.drop(columns=['PublicationDate'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df2 = rename_columns(df_air_releases_national)

df2.dropna(inplace=True)
print(df_air_releases_national.shape)

(13639, 4)

In [11]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df2)

    ----- Shape -----
(13639, 4)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13639 entries, 0 to 13638
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   countryname    13639 non-null  object
 1   reportingyear  13639 non-null  int64
 2   pollutant      13639 non-null  object
 3   releases       13639 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 426.3+ KB
None

    ---- Empty Values ---
countryname      0
reportingyear    0
pollutant        0
releases         0
dtype: int64

    ----- Dtypes -----
countryname       object
reportingyear      int64
pollutant         object
releases         float64
dtype: object

### Air releases sector > df3

In [12]:
df_air_releases_sector = pd.read_csv(config['data']['raw']['file4'])
display(df_air_releases_sector.head())
display(df_air_releases_sector.dtypes)
display(df_air_releases_sector.shape)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,Pollutant,Releases
0,2026/02/13,Norway,2013,3.0,Mineral industry,Mercury and compounds (as Hg),2.500000e+01
1,2026/02/13,Czechia,2014,1.0,Energy sector,Arsenic and compounds (as As),1.363400e+03
2,2026/02/13,Italy,2008,1.0,Energy sector,Nitrogen oxides (NOX),1.039530e+08
3,2026/02/13,Spain,2018,1.0,Energy sector,Carbon dioxide (CO2),7.229500e+10
4,2026/02/13,Serbia,2022,1.0,Energy sector,Sulphur oxides (SOX),3.087640e+08

PublicationDate      object
countryName          object
reportingYear         int64
EPRTR_SectorCode    float64
EPRTR_SectorName     object
Pollutant            object
Releases            float64
dtype: object

(42000, 7)

In [13]:
df_air_releases_sector = df_air_releases_sector.drop(columns=['PublicationDate'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df3 = rename_columns(df_air_releases_national)

df3.dropna(inplace=True)
print(df3.shape)

(13639, 4)

In [14]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df3)

    ----- Shape -----
(13639, 4)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13639 entries, 0 to 13638
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   countryname    13639 non-null  object
 1   reportingyear  13639 non-null  int64
 2   pollutant      13639 non-null  object
 3   releases       13639 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 426.3+ KB
None

    ---- Empty Values ---
countryname      0
reportingyear    0
pollutant        0
releases         0
dtype: int64

    ----- Dtypes -----
countryname       object
reportingyear      int64
pollutant         object
releases         float64
dtype: object

## WATER

### Water facilities > df4

In [15]:
df_water_releases_facilities = pd.read_csv(config['data']['raw']['file2'])
display(df_water_releases_facilities.head())
display(df_water_releases_facilities.dtypes)

C:\Users\fotos\AppData\Local\Temp\ipykernel_17052\3054174240.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_water_releases_facilities = pd.read_csv(config['data']['raw']['file2'])

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason
0,2026/02/13,United Kingdom,2014,1.0,Energy sector,1(c),UK.CAED/BEISOffsh-Forties-Alpha.FACILITY,Forties Alpha,--,0.582170,57.435510,NaN,WATER,Anthracene,12.10,NaN
1,2026/02/13,Germany,2011,4.0,Chemical industry,4(b)(iv),https://registry.gdi-de.org/id/de.nw.inspire.p...,Solvay GmbH,Rheinberg,6.577830,51.564710,NaN,WATER,Cadmium and compounds (as Cd),113.00,NaN
2,2026/02/13,Germany,2022,5.0,Waste and wastewater management,5(f),https://registry.gdi-de.org/id/de.by.inspire.p...,AmperVerband,Olching,11.360499,48.233805,NaN,WATER,Total organic carbon(as total C or COD/3) (TOC),77700.00,NaN
3,2026/02/13,Hungary,2007,5.0,Waste and wastewater management,5(f),HU.OKIR/100609995.FACILITY,Fővárosi Csatornázási Művek Zrt.,Budapest 04. ker.,19.073994,47.572780,NaN,WATER,Mercury and compounds (as Hg),5.05,NaN
4,2026/02/13,Portugal,2014,1.0,Energy sector,1(a),PT.CAED/PT.APA05769662.CI,Refinaria de Sines (CI),SINES,-8.800138,37.963901,NaN,WATER,Total organic carbon(as total C or COD/3) (TOC),62100.00,NaN

PublicationDate                  object
countryName                      object
reportingYear                     int64
EPRTR_SectorCode                float64
EPRTR_SectorName                 object
EPRTRAnnexIMainActivity          object
FacilityInspireId                object
facilityName                     object
city                             object
Longitude                       float64
Latitude                        float64
addressConfidentialityReason     object
TargetRelease                    object
Pollutant                        object
Releases                        float64
confidentialityReason            object
dtype: object

In [16]:
df_water_releases_facilities = df_water_releases_facilities.drop(columns=['PublicationDate'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df4 = rename_columns(df_water_releases_facilities)

df4.dropna(inplace=True)
print(df4.shape)

(0, 15)

In [17]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df4)

    ----- Shape -----
(0, 15)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   countryname                   0 non-null      object
 1   reportingyear                 0 non-null      int64
 2   eprtr_sectorcode              0 non-null      float64
 3   eprtr_sectorname              0 non-null      object
 4   eprtranneximainactivity       0 non-null      object
 5   facilityinspireid             0 non-null      object
 6   facilityname                  0 non-null      object
 7   city                          0 non-null      object
 8   longitude                     0 non-null      float64
 9   latitude                      0 non-null      float64
 10  addressconfidentialityreason  0 non-null      object
 11  targetrelease                 0 non-null      object
 12  pollutant                     0 non-null      object
 13  releases                      0 non-null      float64
 14  confidentialityreason         0 non-null      object
dtypes: float64(4), int64(1), object(10)
memory usage: 0.0+ bytes
None

    ---- Empty Values ---
countryname                     0
reportingyear                   0
eprtr_sectorcode                0
eprtr_sectorname                0
eprtranneximainactivity         0
facilityinspireid               0
facilityname                    0
city                            0
longitude                       0
latitude                        0
addressconfidentialityreason    0
targetrelease                   0
pollutant                       0
releases                        0
confidentialityreason           0
dtype: int64

    ----- Dtypes -----
countryname                      object
reportingyear                     int64
eprtr_sectorcode                float64
eprtr_sectorname                 object
eprtranneximainactivity          object
facilityinspireid                object
facilityname                     object
city                             object
longitude                       float64
latitude                        float64
addressconfidentialityreason     object
targetrelease                    object
pollutant                        object
releases                        float64
confidentialityreason            object
dtype: object

### Water releases national > df5

In [18]:
df_water_releases_national = pd.read_csv(config['data']['raw']['file5'])
display(df_water_releases_national.head())
display(df_water_releases_national.dtypes)
display(df_water_releases_national.shape)

,PublicationDate,countryName,reportingYear,Pollutant,Releases
0,2026/02/13,Italy,2019,Total nitrogen,24776324.60
1,2026/02/13,Belgium,2018,Fluoranthene,3.08
2,2026/02/13,Finland,2013,Phenols (as total C),544.20
3,2026/02/13,Germany,2020,Isoproturon,30.80
4,2026/02/13,Germany,2010,Total phosphorus,1856310.00

PublicationDate     object
countryName         object
reportingYear        int64
Pollutant           object
Releases           float64
dtype: object

(12607, 5)

In [19]:
df_water_releases_national = df_water_releases_national.drop(columns=['PublicationDate'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df5 = rename_columns(df_water_releases_national)

df5.dropna(inplace=True)
print(df5.shape)

(12607, 4)

In [20]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df5)

    ----- Shape -----
(12607, 4)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12607 entries, 0 to 12606
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   countryname    12607 non-null  object
 1   reportingyear  12607 non-null  int64
 2   pollutant      12607 non-null  object
 3   releases       12607 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 394.1+ KB
None

    ---- Empty Values ---
countryname      0
reportingyear    0
pollutant        0
releases         0
dtype: int64

    ----- Dtypes -----
countryname       object
reportingyear      int64
pollutant         object
releases         float64
dtype: object

### Water releases sector > df6

In [21]:
df_water_releases_sector = pd.read_csv(config['data']['raw']['file6'])
display(df_water_releases_sector.head())
display(df_water_releases_sector.dtypes)
display(df_water_releases_sector.shape)

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,Pollutant,Releases
0,2026/02/13,Germany,2024,2.0,Production and processing of metals,Zinc and compounds (as Zn),11370.0
1,2026/02/13,Germany,2013,5.0,Waste and wastewater management,Total nitrogen,38222100.0
2,2026/02/13,Netherlands,2024,5.0,Waste and wastewater management,Cyanides (as total CN),655.0
3,2026/02/13,Sweden,2016,6.0,Paper and wood production and processing,Total nitrogen,1728800.0
4,2026/02/13,Italy,2007,6.0,Paper and wood production and processing,Chromium and compounds (as Cr),452.2

PublicationDate      object
countryName          object
reportingYear         int64
EPRTR_SectorCode    float64
EPRTR_SectorName     object
Pollutant            object
Releases            float64
dtype: object

(33132, 7)

In [22]:
df_water_releases_sector = df_water_releases_sector.drop(columns=['PublicationDate'])
def rename_columns(df):
    df.rename(columns={col : col.strip() for col in df.columns}, inplace = True)
    df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)
    return df

df6 = rename_columns(df_water_releases_sector)

df6.dropna(inplace=True)
print(df6.shape)

(32227, 6)

In [23]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    #print("\n    ---- Statistics ---")
    #return df.describe()
df_info(df6)

    ----- Shape -----
(32227, 6)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
Index: 32227 entries, 0 to 33131
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   countryname       32227 non-null  object
 1   reportingyear     32227 non-null  int64
 2   eprtr_sectorcode  32227 non-null  float64
 3   eprtr_sectorname  32227 non-null  object
 4   pollutant         32227 non-null  object
 5   releases          32227 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.7+ MB
None

    ---- Empty Values ---
countryname         0
reportingyear       0
eprtr_sectorcode    0
eprtr_sectorname    0
pollutant           0
releases            0
dtype: int64

    ----- Dtypes -----
countryname          object
reportingyear         int64
eprtr_sectorcode    float64
eprtr_sectorname     object
pollutant            object
releases            float64
dtype: object

## Air testing

In [24]:
df2.head()

,countryname,reportingyear,pollutant,releases
0,France,2023,Tetrachloroethylene,1.108000e+04
1,Poland,2012,Methane (CH4),4.971020e+08
2,Czechia,2013,Methane (CH4),1.865000e+06
3,Portugal,2024,Pentachlorobenzene,1.070000e+00
4,Bulgaria,2009,Non-methane volatile organic compounds (NMVOC),3.964000e+06

In [25]:
pd_crosstab_df2 = pd.crosstab(index=df2['pollutant'], 
                              columns=df2['countryname'], 
                              values=df2['releases'], 
                              aggfunc='sum').round(0).fillna(0).astype(int)
pd_crosstab_df2

countryname,Austria,Belgium,Bulgaria,Croatia,Cyprus,Czechia,Denmark,Estonia,Finland,France,...,Poland,Portugal,Romania,Serbia,Slovakia,Slovenia,Spain,Sweden,Switzerland,United Kingdom
pollutant,,,,,,,,,,,,,,,,,,,,,
"1,1,1-trichloroethane (TCE-1,1,1)",0,1011,0,0,0,0,0,0,0,610720,...,0,5050,0,0,0,0,290,0,0,46923
"1,1,2,2-tetrachloroethane (TETRACHLOROETHANE-1,1,2,2)",0,16866,0,0,0,0,0,0,0,1470,...,1003,194,0,0,0,0,386,0,109,22805
"1,2,3,4,5,6-hexachlorocyclohexane (HCH)",0,0,0,0,0,0,0,0,0,0,...,0,0,0,87,0,0,0,0,0,0
"1,2-dichloroethane (DCE-1,2)",34070,955800,0,0,0,27136,0,0,0,5961660,...,172210,2170,4050,0,327680,0,250420,277154,5889,3663180
Aldrin,0,0,0,0,0,0,0,0,0,0,...,4010,0,0,1273,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Trichloroethylene (TRI),0,101600,0,0,0,527216,0,0,11600,809760,...,17610,3380,0,0,25430,0,161210,31290,243450,2383010
Trichloromethane,0,295294,0,0,0,0,0,0,0,1116529,...,32455,360050,0,0,0,0,396673,93000,7035,235694
Vinyl chloride,0,346870,0,0,0,43113,0,0,0,4073470,...,296400,88090,63300,0,598000,0,563030,477461,0,960230
Xylenes,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,289110
Zinc and compounds (as Zn),176307,655515,121682,25764,49602,248600,13086,559974,256824,1606100,...,1540060,356490,225534,0,108340,8194,2113823,332110,137844,534517

In [26]:
display(df_air_releases_facilities.facilityname.nunique())
df_air_releases_facilities.facilityname.value_counts()

0

Series([], Name: count, dtype: int64)