In [1]:
import pandas as pd

In [2]:
import pandas as pd
import numpy as np
import yaml
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

### air national

In [3]:
df_air_releases_national = pd.read_csv("https://raw.githubusercontent.com/bibianglez/Final_project/refs/heads/main/data/raw/F1_1_Air_Releases_National.csv")

In [4]:
df_air_releases_national.head()

,PublicationDate,countryName,reportingYear,Pollutant,Releases
0,2026/02/13,France,2023,Tetrachloroethylene,1.108000e+04
1,2026/02/13,Poland,2012,Methane (CH4),4.971020e+08
2,2026/02/13,Czechia,2013,Methane (CH4),1.865000e+06
3,2026/02/13,Portugal,2024,Pentachlorobenzene,1.070000e+00
4,2026/02/13,Bulgaria,2009,Non-methane volatile organic compounds (NMVOC),3.964000e+06

In [5]:
df_air_releases_national.reportingYear.unique()

array([2023, 2012, 2013, 2024, 2009, 2010, 2011, 2014, 2015, 2017, 2008,
       2018, 2007, 2016, 2021, 2020, 2022, 2019])

In [6]:
df_air_releases_national.countryName.unique()

array(['France', 'Poland', 'Czechia', 'Portugal', 'Bulgaria', 'Sweden',
       'Spain', 'Greece', 'Romania', 'United Kingdom', 'Switzerland',
       'Italy', 'Germany', 'Belgium', 'Slovenia', 'Netherlands',
       'Finland', 'Slovakia', 'Cyprus', 'Ireland', 'Hungary', 'Norway',
       'Denmark', 'Luxembourg', 'Estonia', 'Malta', 'Lithuania',
       'Austria', 'Latvia', 'Iceland', 'Croatia', 'Serbia'], dtype=object)

In [7]:
df_air_releases_national.countryName.nunique()

32

### air sector

In [10]:
df_air_releases_sector = pd.read_csv("https://raw.githubusercontent.com/bibianglez/Final_project/refs/heads/main/data/raw/F1_2_Air_Releases_Sector.csv")
df_air_releases_sector.head()

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,Pollutant,Releases
0,2026/02/13,Norway,2013,3.0,Mineral industry,Mercury and compounds (as Hg),2.500000e+01
1,2026/02/13,Czechia,2014,1.0,Energy sector,Arsenic and compounds (as As),1.363400e+03
2,2026/02/13,Italy,2008,1.0,Energy sector,Nitrogen oxides (NOX),1.039530e+08
3,2026/02/13,Spain,2018,1.0,Energy sector,Carbon dioxide (CO2),7.229500e+10
4,2026/02/13,Serbia,2022,1.0,Energy sector,Sulphur oxides (SOX),3.087640e+08

In [11]:
df_air_releases_sector.countryName.unique()

array(['Norway', 'Czechia', 'Italy', 'Spain', 'Serbia', 'United Kingdom',
       'France', 'Slovakia', 'Romania', 'Poland', 'Belgium', 'Germany',
       'Finland', 'Netherlands', 'Slovenia', 'Ireland', 'Portugal',
       'Hungary', 'Denmark', 'Sweden', 'Bulgaria', 'Estonia', 'Austria',
       'Greece', 'Switzerland', 'Luxembourg', 'Cyprus', 'Lithuania',
       'Croatia', 'Latvia', 'Iceland', 'Malta'], dtype=object)

In [12]:
df_air_releases_sector.countryName.nunique()

32

### water national

In [13]:
df_water_releases_national = pd.read_csv("https://raw.githubusercontent.com/bibianglez/Final_project/refs/heads/main/data/raw/F2_1_Water_Releases_National.csv")
df_water_releases_national.head()

,PublicationDate,countryName,reportingYear,Pollutant,Releases
0,2026/02/13,Italy,2019,Total nitrogen,24776324.60
1,2026/02/13,Belgium,2018,Fluoranthene,3.08
2,2026/02/13,Finland,2013,Phenols (as total C),544.20
3,2026/02/13,Germany,2020,Isoproturon,30.80
4,2026/02/13,Germany,2010,Total phosphorus,1856310.00

In [14]:
df_water_releases_national.countryName.nunique()

32

### water sector

In [7]:
df_water_releases_sector = pd.read_csv ("https://raw.githubusercontent.com/bibianglez/Final_project/refs/heads/main/data/raw/F2_2_Water_Releases_Sector.csv")
df_water_releases_sector.head()

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,Pollutant,Releases
0,2026/02/13,Germany,2024,2.0,Production and processing of metals,Zinc and compounds (as Zn),11370.0
1,2026/02/13,Germany,2013,5.0,Waste and wastewater management,Total nitrogen,38222100.0
2,2026/02/13,Netherlands,2024,5.0,Waste and wastewater management,Cyanides (as total CN),655.0
3,2026/02/13,Sweden,2016,6.0,Paper and wood production and processing,Total nitrogen,1728800.0
4,2026/02/13,Italy,2007,6.0,Paper and wood production and processing,Chromium and compounds (as Cr),452.2

In [8]:
df_water_releases_sector.EPRTR_SectorCode.nunique()

9

In [9]:
df_water_releases_sector.countryName.nunique()

32

### big to small csvs

In [10]:
df_IED_installations = pd.read_csv(r"C:\Users\fotos\Desktop\Ironhack\Final_project\Final_project\data\raw_big\F6_1_IED_Installations.csv")
df_IED_installations.head()

,PublicationDate,CountryName,reportingYear,parent_facilityInspireId,EPRTRAnnexIMainActivity,InstallationInspireId,installationName,installationNameConfidentialityReason,City_of_Facility,Longitude,...,permitGranted,dateOfGranting,permitReconsidered,permitUpdated,dateOfLastUpdate,permitURL,RelevantChapter,BATConclusion,BATAEL,BATAELStricterCondition
0,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Glykol-Fabrik,NaN,Ludwigshafen am Rhein,8.43055,...,Yes,1900-01-01,Yes,No,1900-01-01,https://sgdsued.rlp.de/service/genehmigungen-u...,NaN,LVOC,NaN,NaN
1,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Spezialitäten-Fabrik,NaN,Ludwigshafen am Rhein,8.42603,...,Yes,1900-01-01,Yes,No,1900-01-01,https://sgdsued.rlp.de/service/genehmigungen-u...,NaN,CWW,NaN,NaN
2,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Indol-Fabrik,NaN,Ludwigshafen am Rhein,8.43110,...,Yes,1900-01-01,Yes,No,1900-01-01,https://sgdsued.rlp.de/service/genehmigungen-u...,NaN,CWW,NaN,NaN
3,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Primärreformer Ammoniak-IV,NaN,Ludwigshafen am Rhein,8.41466,...,Yes,1900-01-01,No,No,1900-01-01,NaN,ChapterIII,LCP,NaN,NaN
4,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Salmiakgeist-Fabrik,NaN,Ludwigshafen am Rhein,8.42737,...,Yes,1900-01-01,No,No,1900-01-01,https://sgdsued.rlp.de/service/genehmigungen-u...,NaN,CWW,NaN,NaN

In [11]:
df_IED_installations.dtypes

PublicationDate                           object
CountryName                               object
reportingYear                              int64
parent_facilityInspireId                  object
EPRTRAnnexIMainActivity                   object
InstallationInspireId                     object
installationName                          object
installationNameConfidentialityReason     object
City_of_Facility                          object
Longitude                                float64
Latitude                                 float64
addressConfidentialityReason              object
installationStatus                        object
IEDAnnexIMainActivity                     object
IEDMainActivityName                       object
baselineReportIndicator                   object
siteVisitNumber                          float64
siteVisitURL                              object
dateOfStartOfOperation                    object
publicEmissionMonitoring                  object
publicEmissionMonitoringURL               object
permitGranted                             object
dateOfGranting                            object
permitReconsidered                        object
permitUpdated                             object
dateOfLastUpdate                          object
permitURL                                 object
RelevantChapter                           object
BATConclusion                             object
BATAEL                                    object
BATAELStricterCondition                   object
dtype: object

In [12]:
df_IED_installations.City_of_Facility.nunique()

26901

In [13]:
df_IED_installations_cut = df_IED_installations[['PublicationDate', 'CountryName', 'reportingYear', 'installationName', 'City_of_Facility', 'BATConclusion']]

In [14]:
df_IED_installations_cut.to_csv('df_IED_installations_cut.csv', index=False)

In [15]:
df_LCP_Energy_Emissions = pd.read_csv(r"C:\Users\fotos\Desktop\Ironhack\Final_project\Final_project\data\raw_big\F5_2_LCP_Energy_Emissions.csv")
df_LCP_Energy_Emissions.head()

,PublicationDate,countryName,reportingYear,LCPInspireId,installationPartName,installationPartNameConfidentialityReason,City_Of_Facility,addressConfidentialityReason,Longitude,Latitude,featureType,unit,featureValue,confidentialityReason
0,2026/02/13,Germany,2017,https://registry.gdi-de.org/id/de.sn.sax4inspi...,Heizkraftwerk Leipzig Nord,NaN,Leipzig,NaN,12.377450,51.352070,LCPCharacteristics,MW,514.84,NaN
1,2026/02/13,Germany,2017,https://registry.gdi-de.org/id/de.nw.inspire.p...,Kessel 4 (Wasserrohr-Naturlaufkessel) (bivale...,NaN,Duisburg,NaN,6.697170,51.438040,LCPCharacteristics,MW,67.40,NaN
2,2026/02/13,Germany,2018,https://registry.gdi-de.org/id/de.sh/50083712_...,Heizkraftwerk Wedel,NaN,Wedel,NaN,9.724160,53.567000,LCPCharacteristics,MW,712.00,NaN
3,2026/02/13,Germany,2017,https://registry.gdi-de.org/id/de.by.inspire.p...,Heizkraftwerk Erlangen,NaN,Erlangen,NaN,11.002113,49.592519,LCPCharacteristics,MW,266.90,NaN
4,2026/02/13,Lithuania,2020,LT.CAED/110818317.PART2,Druskininkai district boiler,NaN,Druskininkai,NaN,23.986250,53.997513,LCPCharacteristics,MW,88.00,NaN

In [16]:
df_LCP_Energy_Emissions.dtypes

PublicationDate                               object
countryName                                   object
reportingYear                                  int64
LCPInspireId                                  object
installationPartName                          object
installationPartNameConfidentialityReason     object
City_Of_Facility                              object
addressConfidentialityReason                  object
Longitude                                    float64
Latitude                                     float64
featureType                                   object
unit                                          object
featureValue                                 float64
confidentialityReason                         object
dtype: object

In [17]:
df_LCP_Energy_Emissions_cut = df_LCP_Energy_Emissions[['PublicationDate', 'countryName', 'reportingYear', 'installationPartName', 'City_Of_Facility', 'featureType', 'featureValue']]

In [18]:
df_LCP_Energy_Emissions_cut.to_csv('df_LCP_Energy_Emissions_cut.csv', index=False)

In [19]:
df_F4_2_WasteTransfers_Facilities = pd.read_csv(r"C:\Users\fotos\Desktop\Ironhack\Final_project\Final_project\data\raw_big\F4_2_WasteTransfers_Facilities.csv")
df_F4_2_WasteTransfers_Facilities.head()

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,wasteTreatment,wasteClassification,wasteTransfers,confidentialityReason
0,2026/02/13,United Kingdom,2015,5.0,Waste and wastewater management,5(c),GB.EEA/EW_EA-16558.FACILITY,Cherry Lodge Golf Club,Westerham,0.055694,51.30810,NaN,Disposal,NONHW,129000.0,NaN
1,2026/02/13,France,2010,2.0,Production and processing of metals,2(b),FR.CAED/6056.FACILITY,ARCELORMITTAL MAIZIERES RESEARCH,MAIZIERES LES METZ,6.147730,49.21160,NaN,Disposal,HW,212.0,NaN
2,2026/02/13,France,2009,2.0,Production and processing of metals,2(d),FR.EEA/070.00715.FACILITY,Sambre et Meuse,FEIGNIES,3.900000,50.29000,NaN,Disposal,NONHW,2690.0,NaN
3,2026/02/13,Belgium,2016,1.0,Energy sector,1(a),https://data.ied_registry.omgeving.vlaanderen....,VOPAK ENERGY PARK ANTWERP,Antwerpen,4.288400,51.32542,NaN,Recovery,HW,914.0,NaN
4,2026/02/13,France,2012,4.0,Chemical industry,4(d),FR.CAED/3845.FACILITY,NUFARM,GAILLON,1.387100,49.16635,NaN,Disposal,HW,801.0,NaN

In [20]:
df_F4_2_WasteTransfers_Facilities.dtypes

PublicationDate                  object
countryName                      object
reportingYear                     int64
EPRTR_SectorCode                float64
EPRTR_SectorName                 object
EPRTRAnnexIMainActivity          object
FacilityInspireId                object
facilityName                     object
city                             object
Longitude                       float64
Latitude                        float64
addressConfidentialityReason     object
wasteTreatment                   object
wasteClassification              object
wasteTransfers                  float64
confidentialityReason            object
dtype: object

In [21]:
df_F4_2_WasteTransfers_Facilities_cut = df_F4_2_WasteTransfers_Facilities[['PublicationDate', 'countryName', 'reportingYear', 'facilityName', 'city', 'wasteTreatment', 'wasteClassification', 'wasteTransfers']]

In [22]:
df_F4_2_WasteTransfers_Facilities_cut.to_csv('df_F4_2_WasteTransfers_Facilities_cut.csv', index=False)

In [23]:
df_F1_4_Air_Releases_Facilities = pd.read_csv(r"C:\Users\fotos\Desktop\Ironhack\Final_project\Final_project\data\raw_big\F1_4_Air_Releases_Facilities.csv")
df_F1_4_Air_Releases_Facilities.head()

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason
0,2026/02/13,Germany,2013,1.0,Energy sector,1(e),https://registry.gdi-de.org/id/de.nw.inspire.p...,RWE Power AG-Fabrik Fortuna Nord,Bergheim,6.658050,50.986950,NaN,AIR,Sulphur oxides (SOX),824000.0,NaN
1,2026/02/13,Sweden,2020,7.0,Intensive livestock production and aquaculture,7(a)(i),SE.CAED/10017896.Facility,Skåneägg Produktion AB,MÖRARP,12.849550,56.053160,NaN,AIR,Ammonia (NH3),16300.0,NaN
2,2026/02/13,Romania,2013,5.0,Waste and wastewater management,5(d),RO.CAED/104TL0001.FACILITY,SC ECOREC SA,TULCEA,28.769671,45.190459,NaN,AIR,Methane (CH4),269000.0,NaN
3,2026/02/13,Italy,2021,7.0,Intensive livestock production and aquaculture,7(a),IT.CAED/370602036.FACILITY,RONCHETRIN 1,GAZZO VERONESE,11.106667,45.123611,NaN,AIR,Ammonia (NH3),31920.0,NaN
4,2026/02/13,Czechia,2007,1.0,Energy sector,1(c),CZ.MZP.U423/CZ14819275.FACILITY,energetika,Štětí,14.380370,50.462296,NaN,AIR,Sulphur oxides (SOX),507000.0,NaN

In [24]:
df_F1_4_Air_Releases_Facilities.dtypes

PublicationDate                  object
countryName                      object
reportingYear                     int64
EPRTR_SectorCode                float64
EPRTR_SectorName                 object
EPRTRAnnexIMainActivity          object
FacilityInspireId                object
facilityName                     object
city                             object
Longitude                       float64
Latitude                        float64
addressConfidentialityReason     object
TargetRelease                    object
Pollutant                        object
Releases                        float64
confidentialityReason            object
dtype: object

In [25]:
df_F1_4_Air_Releases_Facilities_cut = df_F1_4_Air_Releases_Facilities[['PublicationDate', 'countryName', 'reportingYear', 'EPRTR_SectorName', 'city', 'facilityName', 'TargetRelease', 'Pollutant']]

In [26]:
df_F1_4_Air_Releases_Facilities_cut.head()

,PublicationDate,countryName,reportingYear,EPRTR_SectorName,city,facilityName,TargetRelease,Pollutant
0,2026/02/13,Germany,2013,Energy sector,Bergheim,RWE Power AG-Fabrik Fortuna Nord,AIR,Sulphur oxides (SOX)
1,2026/02/13,Sweden,2020,Intensive livestock production and aquaculture,MÖRARP,Skåneägg Produktion AB,AIR,Ammonia (NH3)
2,2026/02/13,Romania,2013,Waste and wastewater management,TULCEA,SC ECOREC SA,AIR,Methane (CH4)
3,2026/02/13,Italy,2021,Intensive livestock production and aquaculture,GAZZO VERONESE,RONCHETRIN 1,AIR,Ammonia (NH3)
4,2026/02/13,Czechia,2007,Energy sector,Štětí,energetika,AIR,Sulphur oxides (SOX)

In [27]:
df_F1_4_Air_Releases_Facilities_cut.to_csv('df_F1_4_Air_Releases_Facilities_cut.csv', index=False)

In [16]:
df_F2_4_Water_Releases_Facilities = pd.read_csv(r"C:\Users\fotos\Desktop\Ironhack\Final_project\Final_project\data\raw\F2_4_Water_Releases_Facilities.csv")
df_F2_4_Water_Releases_Facilities.head()

C:\Users\fotos\AppData\Local\Temp\ipykernel_18628\3729951901.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_F2_4_Water_Releases_Facilities = pd.read_csv(r"C:\Users\fotos\Desktop\Ironhack\Final_project\Final_project\data\raw\F2_4_Water_Releases_Facilities.csv")

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason
0,2026/02/13,United Kingdom,2014,1.0,Energy sector,1(c),UK.CAED/BEISOffsh-Forties-Alpha.FACILITY,Forties Alpha,--,0.582170,57.435510,NaN,WATER,Anthracene,12.10,NaN
1,2026/02/13,Germany,2011,4.0,Chemical industry,4(b)(iv),https://registry.gdi-de.org/id/de.nw.inspire.p...,Solvay GmbH,Rheinberg,6.577830,51.564710,NaN,WATER,Cadmium and compounds (as Cd),113.00,NaN
2,2026/02/13,Germany,2022,5.0,Waste and wastewater management,5(f),https://registry.gdi-de.org/id/de.by.inspire.p...,AmperVerband,Olching,11.360499,48.233805,NaN,WATER,Total organic carbon(as total C or COD/3) (TOC),77700.00,NaN
3,2026/02/13,Hungary,2007,5.0,Waste and wastewater management,5(f),HU.OKIR/100609995.FACILITY,Fővárosi Csatornázási Művek Zrt.,Budapest 04. ker.,19.073994,47.572780,NaN,WATER,Mercury and compounds (as Hg),5.05,NaN
4,2026/02/13,Portugal,2014,1.0,Energy sector,1(a),PT.CAED/PT.APA05769662.CI,Refinaria de Sines (CI),SINES,-8.800138,37.963901,NaN,WATER,Total organic carbon(as total C or COD/3) (TOC),62100.00,NaN

In [17]:
df_F2_4_Water_Releases_Facilitiescut = df_F2_4_Water_Releases_Facilities[['PublicationDate', 'countryName', 'reportingYear', 'EPRTR_SectorName', 'city', 'facilityName', 'TargetRelease', 'Pollutant']]
df_F2_4_Water_Releases_Facilitiescut.head()

,PublicationDate,countryName,reportingYear,EPRTR_SectorName,city,facilityName,TargetRelease,Pollutant
0,2026/02/13,United Kingdom,2014,Energy sector,--,Forties Alpha,WATER,Anthracene
1,2026/02/13,Germany,2011,Chemical industry,Rheinberg,Solvay GmbH,WATER,Cadmium and compounds (as Cd)
2,2026/02/13,Germany,2022,Waste and wastewater management,Olching,AmperVerband,WATER,Total organic carbon(as total C or COD/3) (TOC)
3,2026/02/13,Hungary,2007,Waste and wastewater management,Budapest 04. ker.,Fővárosi Csatornázási Művek Zrt.,WATER,Mercury and compounds (as Hg)
4,2026/02/13,Portugal,2014,Energy sector,SINES,Refinaria de Sines (CI),WATER,Total organic carbon(as total C or COD/3) (TOC)

In [18]:
df_F2_4_Water_Releases_Facilitiescut.to_csv('df_F2_4_Water_Releases_Facilitiescut.csv', index=False)

In [19]:
df_water_releases = pd.read_csv(r"C:\Users\fotos\Desktop\Ironhack\Final_project\Final_project\data\raw\eea_s_indp005_p_2010-2024_v02_r00.csv")
df_water_releases.head()

,eu_sdg,dimension,dimension_label,unit,unit_label,geo,geo_label,time,obs_value,obs_status
0,indp005,INDP_W_HM,Industrial pollutant releases to water in Euro...,I10,"Index, 2010 = 100",EU27_2020,European Union - 27 countries (from 2020),2010,100.0,NaN
1,indp005,INDP_W_HM,Industrial pollutant releases to water in Euro...,I10,"Index, 2010 = 100",EU27_2020,European Union - 27 countries (from 2020),2011,94.0,NaN
2,indp005,INDP_W_HM,Industrial pollutant releases to water in Euro...,I10,"Index, 2010 = 100",EU27_2020,European Union - 27 countries (from 2020),2012,95.0,NaN
3,indp005,INDP_W_HM,Industrial pollutant releases to water in Euro...,I10,"Index, 2010 = 100",EU27_2020,European Union - 27 countries (from 2020),2013,95.0,NaN
4,indp005,INDP_W_HM,Industrial pollutant releases to water in Euro...,I10,"Index, 2010 = 100",EU27_2020,European Union - 27 countries (from 2020),2014,102.0,NaN

In [3]:
import geopandas as gpd

In [5]:
gdf = gpd.read_file(config['data']['raw']['file7'])

display(gdf.head())

D:\Anaconda\Lib\site-packages\geopandas\io\file.py:576: UserWarning: Error parsing datetimes, original strings are returned: Out of bounds nanosecond timestamp: 1000-01-01, at position 153. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
  return pyogrio.read_dataframe(path_or_bytes, bbox=bbox, **kwargs)
D:\Anaconda\Lib\site-packages\geopandas\io\file.py:576: UserWarning: Error parsing datetimes, original strings are returned: Out of bounds nanosecond timestamp: 1000-01-01, at position 593. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.
  return pyogrio.read_dataframe(path_or_bytes, bbox=bbox, **kwargs)

,OBJECTID,id,x_4258,y_4258,pollutants,num_pollutants,air_groups,water_groups,dateOfLatestOpStart,dateOfLatestPermit,...,has_ophours_data,has_seveso,count_factype_EPRTR,count_factype_NONEPRTR,count_instype_IED,count_instype_NONIED,count_plantType_LCP,count_plantType_coWI,count_plantType_WI,geometry
0,1,1267934,-3.0850,48.2635,None,0,None,None,None,1900-01-01,...,0,0,1,1,1,0,0,0,0,POINT (-343420 6150804)
1,2,1267935,-3.3804,48.6403,None,0,None,None,None,1900-01-01,...,0,0,0,1,1,0,0,0,0,POINT (-376304 6214046)
2,3,1267936,-3.2409,48.7187,None,0,None,None,None,1900-01-01,...,0,0,1,1,1,0,0,0,0,POINT (-360775 6227264)
3,4,1267937,-2.8254,48.5697,None,0,None,None,None,1900-01-01,...,0,0,1,1,1,0,0,0,0,POINT (-314522 6202161)
4,5,1267938,-3.1265,48.7138,None,0,None,None,None,1900-01-01,...,0,0,0,1,1,0,0,0,0,POINT (-348040 6226438)

In [12]:
gdf.pollutants.nunique()

41477

In [13]:
gdf.pollutants.unique()

array([None, 'Methane (CH4)',
       'Fluorine and inorganic compounds (as HF), Sulphur oxides (SOX)',
       ...,
       'Total phosphorus, Nonylphenol and Nonylphenol ethoxylates, Arsenic and compounds (as As), Di-(2-ethyl hexyl) phthalate (DEHP), Zinc and compounds (as Zn), Total nitrogen, Nickel and compounds (as Ni)',
       'Total phosphorus, Naphthalene, Arsenic and compounds (as As), Zinc and compounds (as Zn), Total organic carbon(as total C or COD/3) (TOC), Asbestos, Di-(2-ethyl hexyl) phthalate (DEHP), Total nitrogen, Nonylphenol and Nonylphenol ethoxylates, Halogenated organic compounds (as AOX), Copper and compounds (as Cu), Fluorides (as total F), Nickel and compounds (as Ni)',
       'Vinyl chloride, Hydro-fluorocarbons (HFCS), Nitrogen oxides (NOX)'],
      shape=(41478,), dtype=object)

In [14]:
gdf.num_pollutants.nunique()

44

In [15]:
gdf.num_pollutants.unique()

array([ 0,  1,  2,  8,  4,  7,  5,  3, 10,  9,  6, 13, 21, 12, 20, 14, 15,
       16, 11, 17, 23, 19, 18, 28, 26, 32, 25, 22, 27, 35, 31, 24, 29, 33,
       34, 50, 36, 30, 43, 47, 41, 37, 39, 38])

In [16]:
gdf.dtypes

OBJECTID                     int64
id                           int64
x_4258                     float64
y_4258                     float64
pollutants                  object
num_pollutants               int64
air_groups                  object
water_groups                object
dateOfLatestOpStart         object
dateOfLatestPermit          object
numInspections               int64
permit_years                object
permit_types                object
bat_conclusions             object
bat_conclusion_years        object
eprtr_sectors               object
eea_activities              object
activity_details            object
eprtr_AnnexIActivity        object
Site_reporting_year          int64
siteName                    object
InspireSiteId               object
countryCode                 object
nuts_regions                object
cities                      object
rbds                        object
nFacilities                  int64
nInstallations               int64
nLCP                         int64
facilityTypes               object
facilityNames               object
installationTypes           object
plantTypes                  object
has_facilities               int64
has_installations            int64
has_lcps                     int64
has_transfer_data            int64
has_release_data             int64
has_waste_data               int64
has_fuel_data                int64
has_ophours_data             int64
has_seveso                   int64
count_factype_EPRTR          int64
count_factype_NONEPRTR       int64
count_instype_IED            int64
count_instype_NONIED         int64
count_plantType_LCP          int64
count_plantType_coWI         int64
count_plantType_WI           int64
geometry                  geometry
dtype: object

In [27]:
geo_df = gdf[['OBJECTID', 'x_4258', 'y_4258', 'pollutants', 'num_pollutants', 'air_groups', 'water_groups', 'eprtr_sectors','activity_details', 'siteName','countryCode', 'nuts_regions', 'cities', 'rbds', 'nLCP', 'has_release_data', 'geometry']]
geo_df.head(5)

,OBJECTID,x_4258,y_4258,pollutants,num_pollutants,air_groups,water_groups,eprtr_sectors,activity_details,siteName,countryCode,nuts_regions,cities,rbds,nLCP,has_release_data,geometry
0,1,-3.0850,48.2635,None,0,None,None,None,None,SARL PECHARD,FR,"FRH0,FRH,FRH01",PLUSSULIEN,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (-343420 6150804)
1,2,-3.3804,48.6403,None,0,None,None,None,None,EARL DES ALIZES,FR,"FRH01,FRH,FRH0",PLUZUNET,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,0,POINT (-376304 6214046)
2,3,-3.2409,48.7187,None,0,None,None,None,None,SA COUVOIR PERROT,FR,"FRH,FRH0,FRH01",LA ROCHE-JAUDY,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,0,POINT (-360775 6227264)
3,4,-2.8254,48.5697,None,0,None,None,None,None,SARL STATION AVICOLE DE LA VILLE AU DORE,FR,"FRH01,FRH,FRH0",PORDIC,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (-314522 6202161)
4,5,-3.1265,48.7138,None,0,None,None,None,None,SCEA LE ROY PHILIPPE,FR,"FRH,FRH01,FRH0",QUEMPER GUEZENNEC,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,0,POINT (-348040 6226438)

In [19]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    print("\n    ---- Statistics ---")
    return df.describe()
df_info(geo_df)

    ----- Shape -----
(854730, 17)

    ---- df info ---
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 854730 entries, 0 to 854729
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   OBJECTID          854730 non-null  int64
 1   x_4258            854730 non-null  float64
 2   y_4258            854730 non-null  float64
 3   pollutants        242066 non-null  object
 4   num_pollutants    854730 non-null  int64
 5   air_groups        233992 non-null  object
 6   water_groups      79339 non-null   object
 7   eprtr_sectors     769677 non-null  object
 8   activity_details  769677 non-null  object
 9   siteName          854730 non-null  object
 10  countryCode       854730 non-null  object
 11  nuts_regions      841596 non-null  object
 12  cities            852881 non-null  object
 13  rbds              844324 non-null  object
 14  nLCP              854730 non-null  int64
 15  has_release_data  854730 non-null  int64
 16  geometry          854721 non-null  geometry
dtypes: float64(2), geometry(1), int64(4), object(10)
memory usage: 110.9+ MB
None

    ---- Empty Values ---
OBJECTID                 0
x_4258                   0
y_4258                   0
pollutants          612664
num_pollutants           0
air_groups          620738
water_groups        775391
eprtr_sectors        85053
activity_details     85053
siteName                 0
countryCode              0
nuts_regions         13134
cities                1849
rbds                 10406
nLCP                     0
has_release_data         0
geometry                 9
dtype: int64

    ----- Dtypes -----
OBJECTID               int64
x_4258               float64
y_4258               float64
pollutants            object
num_pollutants         int64
air_groups            object
water_groups          object
eprtr_sectors         object
activity_details      object
siteName              object
countryCode           object
nuts_regions          object
cities                object
rbds                  object
nLCP                   int64
has_release_data       int64
geometry            geometry
dtype: object

    ---- Statistics ---

,OBJECTID,x_4258,y_4258,num_pollutants,nLCP,has_release_data
count,854730.000000,854730.000000,854730.000000,854730.000000,854730.000000,854730.000000
mean,427365.500000,7.276418,48.858302,0.718000,0.038120,0.425488
std,246739.442131,8.890141,5.820368,2.085666,0.345698,0.494417
min,1.000000,-63.082270,-21.322120,0.000000,0.000000,0.000000
25%,213683.250000,-0.144992,45.268300,0.000000,0.000000,0.000000
50%,427365.500000,7.390225,49.583584,0.000000,0.000000,0.000000
75%,641047.750000,12.805008,52.199295,1.000000,0.000000,1.000000
max,854730.000000,56.895200,71.569440,50.000000,41.000000,1.000000

In [20]:
geo_df.to_csv('geo_df.csv', index=False, encoding='utf-8')

In [29]:
df_filtrado = geo_df[
    (geo_df['pollutants'].notna()) & 
    (geo_df['pollutants'] != 'None') & 
    (geo_df['num_pollutants'] >= 0)
].copy()

print(f"original shape: {len(geo_df)}")
print(f"filtered rows: {len(df_filtrado)}")
display(df_filtrado[['pollutants', 'num_pollutants']].head())

original shape: 854730
filtered rows: 242066

                                            pollutants  num_pollutants
93                                       Methane (CH4)               1
97   Fluorine and inorganic compounds (as HF), Sulp...               2
101    Total organic carbon(as total C or COD/3) (TOC)               1
102  Benzene, Carbon monoxide (CO), Carbon dioxide ...               8
109  Nitrogen oxides (NOX), Arsenic and compounds (...               4

In [24]:
geo_df.air_groups.unique()

array([None, 'Greenhouse gases', 'Other gases,Inorganic substances', ...,
       'Heavy metals,Other gases,Greenhouse gases,Other organic substances,Chlorinated organic substances,Inorganic substances',
       'Other gases,Greenhouse gases,Chlorinated organic substances,Other organic substances,Inorganic substances,Heavy metals',
       'Inorganic substances,Chlorinated organic substances,Other gases,Other organic substances,Heavy metals,Greenhouse gases'],
      shape=(1392,), dtype=object)

In [25]:
geo_df.water_groups.unique()

array([None, 'Inorganic substances', 'Other organic substances',
       'Inorganic substances,Heavy metals',
       'Inorganic substances,Other organic substances',
       'Heavy metals,Other organic substances',
       'Other organic substances,Heavy metals', 'Heavy metals',
       'Heavy metals,Inorganic substances,Chlorinated organic substances',
       'Other organic substances,Heavy metals,Inorganic substances',
       'Heavy metals,Other organic substances,Inorganic substances',
       'Inorganic substances,Other organic substances,Heavy metals',
       'Heavy metals,Inorganic substances,Other organic substances',
       'Other organic substances,Inorganic substances',
       'Other organic substances,Inorganic substances,Heavy metals',
       'Inorganic substances,Heavy metals,Other organic substances',
       'Other organic substances,Inorganic substances,Chlorinated organic substances',
       'Chlorinated organic substances,Heavy metals,Inorganic substances,Other organic substances',
       'Other organic substances,Heavy metals,Inorganic substances,Chlorinated organic substances',
       'Inorganic substances,Other organic substances,Chlorinated organic substances,Heavy metals',
       'Inorganic substances,Heavy metals,Chlorinated organic substances',
       'Chlorinated organic substances,Inorganic substances',
       'Chlorinated organic substances',
       'Inorganic substances,Chlorinated organic substances,Heavy metals',
       'Heavy metals,Inorganic substances',
       'Chlorinated organic substances,Other organic substances,Inorganic substances,Heavy metals',
       'Chlorinated organic substances,Heavy metals,Other organic substances,Inorganic substances',
       'Other organic substances,Chlorinated organic substances,Inorganic substances,Heavy metals',
       'Heavy metals,Chlorinated organic substances,Inorganic substances',
       'Inorganic substances,Chlorinated organic substances,Heavy metals,Other organic substances',
       'Heavy metals,Chlorinated organic substances',
       'Inorganic substances,Chlorinated organic substances',
       'Heavy metals,Other organic substances,Chlorinated organic substances,Inorganic substances',
       'Heavy metals,Chlorinated organic substances,Other organic substances,Inorganic substances',
       'Chlorinated organic substances,Inorganic substances,Heavy metals,Other organic substances',
       'Chlorinated organic substances,Other organic substances,Heavy metals',
       'Inorganic substances,Chlorinated organic substances,Other organic substances,Heavy metals',
       'Other organic substances,Inorganic substances,Chlorinated organic substances,Heavy metals',
       'Chlorinated organic substances,Heavy metals,Other organic substances',
       'Inorganic substances,Other organic substances,Heavy metals,Chlorinated organic substances',
       'Heavy metals,Other organic substances,Inorganic substances,Chlorinated organic substances',
       'Chlorinated organic substances,Other organic substances',
       'Inorganic substances,Heavy metals,Other organic substances,Chlorinated organic substances',
       'Heavy metals,Inorganic substances,Other organic substances,Chlorinated organic substances',
       'Chlorinated organic substances,Heavy metals',
       'Other organic substances,Chlorinated organic substances,Heavy metals,Inorganic substances',
       'Other organic substances,Heavy metals,Chlorinated organic substances,Inorganic substances',
       'Other organic substances,Chlorinated organic substances',
       'Other organic substances,Inorganic substances,Heavy metals,Chlorinated organic substances',
       'Other organic substances,Heavy metals,Chlorinated organic substances',
       'Chlorinated organic substances,Inorganic substances,Other organic substances,Heavy metals',
       'Inorganic substances,Heavy metals,Chlorinated organic substances,Other organic substances',
       'Chlorinated organic substances,Other organic substances,Inorganic substances',
       'Other organic substances,Chlorinated organic substances,Inorganic substances',
       'Heavy metals,Chlorinated organic substances,Other organic substances',
       'Chlorinated organic substances,Inorganic substances,Heavy metals',
       'Heavy metals,Chlorinated organic substances,Inorganic substances,Other organic substances',
       'Inorganic substances,Other organic substances,Chlorinated organic substances',
       'Heavy metals,Other organic substances,Chlorinated organic substances',
       'Chlorinated organic substances,Heavy metals,Inorganic substances',
       'Chlorinated organic substances,Other organic substances,Heavy metals,Inorganic substances',
       'Chlorinated organic substances,Inorganic substances,Other organic substances',
       'Heavy metals,Inorganic substances,Chlorinated organic substances,Other organic substances',
       'Other organic substances,Chlorinated organic substances,Heavy metals',
       'Inorganic substances,Chlorinated organic substances,Other organic substances'],
      dtype=object)

In [30]:
df_filtrado.head(25)

,OBJECTID,x_4258,y_4258,pollutants,num_pollutants,air_groups,water_groups,eprtr_sectors,activity_details,siteName,countryCode,nuts_regions,cities,rbds,nLCP,has_release_data,geometry
93,94,0.40836,46.45758,Methane (CH4),1,Greenhouse gases,None,WASTE AND WASTEWATER,Landfills (excluding landfills of inert waste ...,SOVAL NORD - ISDND DE GIZAY,FR,"FRI3,FRI,FRI34",GIZAY,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (45458 5853982)
97,98,0.57579,45.89630,"Fluorine and inorganic compounds (as HF), Sulp...",2,"Other gases,Inorganic substances",Inorganic substances,MINERALS,Installations for the manufacture of ceramic p...,MONIER,FR,"FRI,FRI31,FRI3",ROUMAZIERES LOUBERT,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/F...,0,1,POINT (64096 5763746)
101,102,-0.18053,46.77984,Total organic carbon(as total C or COD/3) (TOC),1,None,Other organic substances,FOOD AND BEVERAGE,Treatment and processing of milk,FROMAGERIES LESCURE USINE DE ST-LOUP,FR,"FRI33,FRI,FRI3",ST LOUP LAMAIRE,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (-20096 5906212)
102,103,-0.14459,46.80699,"Benzene, Carbon monoxide (CO), Carbon dioxide ...",8,"Greenhouse gases,Other organic substances,Othe...",Other organic substances,MINERALS,Installations for the production of cement cli...,CIMENTS CALCIA - SITE D'AIRVAULT,FR,"FRI33,FRI3,FRI",AIRVAULT,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (-16095 5910626)
109,110,-0.32005,45.69330,"Nitrogen oxides (NOX), Arsenic and compounds (...",4,"Other gases,Inorganic substances,Heavy metals","Inorganic substances,Heavy metals",MINERALS,"Installations for the manufacture of glass, in...",VERALLIA,FR,"FRI3,FRI31,FRI",COGNAC,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/F...,0,1,POINT (-35627 5731335)
110,111,0.10698,45.64660,Total organic carbon(as total C or COD/3) (TOC),1,None,Other organic substances,PAPER AND WOOD,Industrial plants for the production of paper ...,PAPETERIE SAINT-MICHEL,FR,"FRI31,FRI3,FRI",ST MICHEL,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/F...,0,1,POINT (11908 5723896)
111,112,-0.15186,45.46798,Non-methane volatile organic compounds (NMVOC),1,Other gases,None,OTHER,Installations for the surface treatment of sub...,AMCOR FLEXIBLES BARBEZIEUX,FR,"FRI31,FRI3,FRI",BARBEZIEUX ST HILAIRE,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/F...,0,1,POINT (-16904 5695498)
112,113,0.50548,44.84450,Total organic carbon(as total C or COD/3) (TOC...,2,None,"Inorganic substances,Other organic substances",CHEMICALS,Chemical installations for the production on a...,MANUCO,FR,"FRI11,FRI1,FRI",BERGERAC,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/F...,0,1,POINT (56269 5597074)
136,137,-0.37432,45.68270,"Copper and compounds (as Cu), Total organic ca...",2,Heavy metals,"Heavy metals,Other organic substances",WASTE AND WASTEWATER,Installations for the disposal of non-hazardou...,REVICO,FR,"FRI,FRI31,FRI3",ST LAURENT DE COGNAC,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/F...,0,1,POINT (-41669 5729646)
139,140,0.37723,46.29211,Methane (CH4),1,Greenhouse gases,None,WASTE AND WASTEWATER,Landfills (excluding landfills of inert waste ...,SUEZ - INSTALLATION DE STOCKAGE DE DÉCHETS NON...,FR,"FRI,FRI34,FRI3",SOMMIERES DU CLAIN,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (41993 5827284)
140,141,0.67213,46.83198,Methane (CH4),1,Greenhouse gases,None,WASTE AND WASTEWATER,Landfills (excluding landfills of inert waste ...,SUEZ R&V SUD OUEST - INSTALLATION DE STOCKAGE ...,FR,"FRI34,FRI3,FRI",ST SAUVEUR,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (74821 5914691)
143,144,0.58585,46.23898,Methane (CH4),1,Greenhouse gases,None,WASTE AND WASTEWATER,Landfills (excluding landfills of inert waste ...,SÉCHÉ ECO-INDUSTRIES,FR,"FRI3,FRI,FRI34",LE VIGEANT,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (65216 5818728)
165,166,-0.36424,45.22600,"Nitrous oxide (N2O), Mercury and compounds (as...",8,"Greenhouse gases,Other gases,Other organic sub...","Other organic substances,Heavy metals",MINERALS,Installations for the production of cement cli...,CIMENTS CALCIA - SITE DE BUSSAC,FR,"FRI3,FRI32,FRI",BUSSAC FORET,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/F...,0,1,POINT (-40547 5657171)
176,177,-0.41308,45.98090,Zinc and compounds (as Zn),1,Heavy metals,Heavy metals,WASTE AND WASTEWATER,Installations for the incineration of non-haza...,CYCLERGIE ETS SAINTONGE,FR,"FRI,FRI3,FRI32",PAILLE,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/F...,0,1,POINT (-45983 5777288)
177,178,-0.13352,46.81776,Non-methane volatile organic compounds (NMVOC),1,Other gases,None,OTHER,Installations for the surface treatment of sub...,SOCOPLAN,FR,"FRI33,FRI3,FRI",AIRVAULT,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (-14863 5912378)
185,186,-0.33086,46.74874,Methane (CH4),1,Greenhouse gases,None,WASTE AND WASTEWATER,Landfills (excluding landfills of inert waste ...,SUEZ R&V SUD OUEST - INSTALLATION DE STOCKAGE ...,FR,"FRI33,FRI,FRI3",AMAILLOUX,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (-36831 5901158)
186,187,-0.00509,45.09930,Ammonia (NH3),1,Other gases,None,WASTE AND WASTEWATER,Installations for the disposal of non-hazardou...,SAS PAPREC AGRO,FR,"FRI1,FRI12,FRI",ST CHRISTOPHE DE DOUBLE,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/F...,0,1,POINT (-566 5637167)
195,196,-0.06656,46.36957,Ammonia (NH3),1,Other gases,None,INTENSIVE LIVESTOCK,Installations for the intensive rearing of pou...,SCEA PLAINE DE BOUILLEES SITE VALLEE BARBIER,FR,"FRI3,FRI,FRI33",PAMPROUX,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/G...,0,1,POINT (-7409 5839772)
205,206,8.75774,41.93050,"Sulphur oxides (SOX), Carbon monoxide (CO), Pa...",7,"Other gases,Greenhouse gases,Other organic sub...","Other organic substances,Heavy metals",ENERGY,Thermal power stations and other combustion in...,CENTRALE THERMIQUE DU VAZZIO,FR,"FRM01,FRM,FRM0",AJACCIO,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/E...,3,1,POINT (974907 5150574)
210,211,8.95160,41.68163,Methane (CH4),1,Greenhouse gases,None,WASTE AND WASTEWATER,Landfills (excluding landfills of inert waste ...,SM POUR LA VALORISATION DES DÉCHETS (SYVADEC),FR,"FRM01,FRM0,FRM",VIGGIANELLO,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/E...,0,1,POINT (996487 5113407)
212,213,9.44700,42.52800,"Sulphur oxides (SOX), Ammonia (NH3), Nitrogen ...",5,"Heavy metals,Greenhouse gases,Other gases",Heavy metals,ENERGY,Thermal power stations and other combustion in...,EDF PRODUCTION ELECTRIQUE INSULAIRE - ETABLISS...,FR,"FRM0,FRM,FRM02",LUCCIANA,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/E...,1,1,POINT (1051635 5240402)
214,215,2.50666,48.77046,"Chlorine and inorganic compounds (as HCl), Nit...",4,"Heavy metals,Other gases,Inorganic substances","Inorganic substances,Heavy metals",MINERALS,"Installations for the manufacture of glass, in...",SGD USINE DE SUCY EN BRIE,FR,"FR1,FR10,FR107",SUCY EN BRIE,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/H...,0,1,POINT (279040 6236002)
219,220,2.41632,48.78900,"Carbon dioxide (CO2), Nitrogen oxides (NOX), N...",3,"Greenhouse gases,Other gases",None,ENERGY,Thermal power stations and other combustion in...,SNC COGÉ VITRY,FR,"FR1,FR107,FR10",VITRY SUR SEINE,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/H...,1,1,POINT (268983 6239134)
220,221,2.24810,48.93347,Tetrachloroethylene,1,Other organic substances,Other organic substances,METALS,Installations for surface treatment of metals ...,SAFRAN TRANSMISSION SYSTEMS COLOMBES,FR,"FR10,FR1,FR105",COLOMBES,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/H...,0,1,POINT (250257 6263580)
221,222,2.24772,48.93324,Nitrous oxide (N2O),1,Greenhouse gases,None,WASTE AND WASTEWATER,Installations for the incineration of non-haza...,SIAAP USINE SEINE CENTRE,FR,"FR10,FR105,FR1",COLOMBES,http://id.eaufrance.fr/DisctrictDCE_VRAP2022/H...,0,1,POINT (250215 6263541)

In [31]:
IED = pd.read_csv(r"C:\Users\fotos\Desktop\Ironhack\Final_project\Final_project\data\raw_big\F6_1_IED_Installations.csv")
IED.head()

,PublicationDate,CountryName,reportingYear,parent_facilityInspireId,EPRTRAnnexIMainActivity,InstallationInspireId,installationName,installationNameConfidentialityReason,City_of_Facility,Longitude,...,permitGranted,dateOfGranting,permitReconsidered,permitUpdated,dateOfLastUpdate,permitURL,RelevantChapter,BATConclusion,BATAEL,BATAELStricterCondition
0,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Glykol-Fabrik,NaN,Ludwigshafen am Rhein,8.43055,...,Yes,1900-01-01,Yes,No,1900-01-01,https://sgdsued.rlp.de/service/genehmigungen-u...,NaN,LVOC,NaN,NaN
1,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Spezialitäten-Fabrik,NaN,Ludwigshafen am Rhein,8.42603,...,Yes,1900-01-01,Yes,No,1900-01-01,https://sgdsued.rlp.de/service/genehmigungen-u...,NaN,CWW,NaN,NaN
2,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Indol-Fabrik,NaN,Ludwigshafen am Rhein,8.43110,...,Yes,1900-01-01,Yes,No,1900-01-01,https://sgdsued.rlp.de/service/genehmigungen-u...,NaN,CWW,NaN,NaN
3,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Primärreformer Ammoniak-IV,NaN,Ludwigshafen am Rhein,8.41466,...,Yes,1900-01-01,No,No,1900-01-01,NaN,ChapterIII,LCP,NaN,NaN
4,2026/02/13,Germany,2023,https://registry.gdi-de.org/id/de.rp.inspire.p...,4(a)(ii),https://registry.gdi-de.org/id/de.rp.inspire.p...,Salmiakgeist-Fabrik,NaN,Ludwigshafen am Rhein,8.42737,...,Yes,1900-01-01,No,No,1900-01-01,https://sgdsued.rlp.de/service/genehmigungen-u...,NaN,CWW,NaN,NaN

In [33]:
air_annex = pd.read_csv(r"C:\Users\fotos\Desktop\Ironhack\Final_project\Final_project\data\raw\F1_3_Air_Releases_AnnexIActivity.csv")
air_annex.head()

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,Pollutant,Releases
0,2026/02/13,United Kingdom,2008,1.0,Energy sector,1(a),Carbon dioxide (CO2),1.563100e+10
1,2026/02/13,Germany,2009,3.0,Mineral industry,3(a),Nitrogen oxides (NOX),1.251000e+06
2,2026/02/13,Romania,2022,2.0,Production and processing of metals,2(b),Non-methane volatile organic compounds (NMVOC),1.760000e+05
3,2026/02/13,Spain,2017,8.0,Animal and vegetable products from the food an...,8(b)(i),Nitrogen oxides (NOX),2.008000e+06
4,2026/02/13,United Kingdom,2007,2.0,Production and processing of metals,2(e),PCDD + PCDF (dioxins + furans) (as Teq),1.579000e-03