In [2]:
import pandas as pd
import eurostat

In [3]:
table_code = 'demo_r_mlifexp'
df_life_exp = eurostat.get_data_df(table_code)
display(df_life_exp.head())

,freq,unit,sex,age,geo\TIME_PERIOD,1990,1991,1992,1993,1994,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,YR,F,Y1,AL,NaN,NaN,NaN,NaN,NaN,...,79.2,79.8,79.7,80.2,80.4,79.4,77.2,80.3,NaN,81.8
1,A,YR,F,Y1,AL0,NaN,NaN,NaN,NaN,NaN,...,79.2,79.8,79.7,80.2,80.4,79.4,NaN,NaN,NaN,81.8
2,A,YR,F,Y1,AL01,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,80.1,79.2,NaN,NaN,NaN,80.5
3,A,YR,F,Y1,AL02,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,83.2,81.3,NaN,NaN,NaN,82.2
4,A,YR,F,Y1,AL03,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,78.4,77.9,NaN,NaN,NaN,82.3

In [4]:
df_life_exp.rename(columns={col : col.strip() for col in df_life_exp.columns}, inplace = True)
df_life_exp.rename(columns={col : col.replace("\\", "_").lower() for col in df_life_exp.columns}, inplace = True)
df_life_exp.shape

(144018, 40)

In [5]:
df_life_exp.dtypes

freq                object
unit                object
sex                 object
age                 object
geo_time_period     object
1990               float64
1991               float64
1992               float64
1993               float64
1994               float64
1995               float64
1996               float64
1997               float64
1998               float64
1999               float64
2000               float64
2001               float64
2002               float64
2003               float64
2004               float64
2005               float64
2006               float64
2007               float64
2008               float64
2009               float64
2010               float64
2011               float64
2012               float64
2013               float64
2014               float64
2015               float64
2016               float64
2017               float64
2018               float64
2019               float64
2020               float64
2021               float64
2022               float64
2023               float64
2024               float64
dtype: object

In [7]:
df_life_exp_clean = df_life_exp.drop(columns=['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009'])
df_life_exp_clean.head()

,freq,unit,sex,age,geo_time_period,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,YR,F,Y1,AL,NaN,NaN,NaN,NaN,79.9,79.2,79.8,79.7,80.2,80.4,79.4,77.2,80.3,NaN,81.8
1,A,YR,F,Y1,AL0,NaN,NaN,NaN,NaN,79.9,79.2,79.8,79.7,80.2,80.4,79.4,NaN,NaN,NaN,81.8
2,A,YR,F,Y1,AL01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.1,79.2,NaN,NaN,NaN,80.5
3,A,YR,F,Y1,AL02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.2,81.3,NaN,NaN,NaN,82.2
4,A,YR,F,Y1,AL03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78.4,77.9,NaN,NaN,NaN,82.3

In [9]:
df_life_exp_clean.geo_time_period.unique()

array(['AL', 'AL0', 'AL01', 'AL02', 'AL03', 'AT', 'AT1', 'AT11', 'AT12',
       'AT13', 'AT2', 'AT21', 'AT22', 'AT3', 'AT31', 'AT32', 'AT33',
       'AT34', 'BE', 'BE1', 'BE10', 'BE2', 'BE21', 'BE22', 'BE23', 'BE24',
       'BE25', 'BE3', 'BE31', 'BE32', 'BE33', 'BE34', 'BE35', 'BG', 'BG3',
       'BG31', 'BG32', 'BG33', 'BG34', 'BG4', 'BG41', 'BG42', 'CH', 'CH0',
       'CH01', 'CH02', 'CH03', 'CH04', 'CH05', 'CH06', 'CH07', 'CY',
       'CY0', 'CY00', 'CZ', 'CZ0', 'CZ01', 'CZ02', 'CZ03', 'CZ04', 'CZ05',
       'CZ06', 'CZ07', 'CZ08', 'DE', 'DE1', 'DE11', 'DE12', 'DE13',
       'DE14', 'DE2', 'DE21', 'DE22', 'DE23', 'DE24', 'DE25', 'DE26',
       'DE27', 'DE3', 'DE30', 'DE4', 'DE40', 'DE5', 'DE50', 'DE6', 'DE60',
       'DE7', 'DE71', 'DE72', 'DE73', 'DE8', 'DE80', 'DE9', 'DE91',
       'DE92', 'DE93', 'DE94', 'DEA', 'DEA1', 'DEA2', 'DEA3', 'DEA4',
       'DEA5', 'DEB', 'DEB1', 'DEB2', 'DEB3', 'DEC', 'DEC0', 'DED',
       'DED2', 'DED4', 'DED5', 'DEE', 'DEE0', 'DEF', 'DEF0', 'DEG',
       'DEG0', 'DK', 'DK0', 'DK01', 'DK02', 'DK03', 'DK04', 'DK05', 'EE',
       'EE0', 'EE00', 'EL', 'EL3', 'EL30', 'EL4', 'EL41', 'EL42', 'EL43',
       'EL5', 'EL51', 'EL52', 'EL53', 'EL54', 'EL6', 'EL61', 'EL62',
       'EL63', 'EL64', 'EL65', 'ES', 'ES1', 'ES11', 'ES12', 'ES13', 'ES2',
       'ES21', 'ES22', 'ES23', 'ES24', 'ES3', 'ES30', 'ES4', 'ES41',
       'ES42', 'ES43', 'ES5', 'ES51', 'ES52', 'ES53', 'ES6', 'ES61',
       'ES62', 'ES63', 'ES64', 'ES7', 'ES70', 'FI', 'FI1', 'FI19', 'FI1B',
       'FI1C', 'FI1D', 'FI2', 'FI20', 'FR', 'FR1', 'FR10', 'FRB', 'FRB0',
       'FRC', 'FRC1', 'FRC2', 'FRD', 'FRD1', 'FRD2', 'FRE', 'FRE1',
       'FRE2', 'FRF', 'FRF1', 'FRF2', 'FRF3', 'FRG', 'FRG0', 'FRH',
       'FRH0', 'FRI', 'FRI1', 'FRI2', 'FRI3', 'FRJ', 'FRJ1', 'FRJ2',
       'FRK', 'FRK1', 'FRK2', 'FRL', 'FRL0', 'FRM', 'FRM0', 'FRY', 'FRY1',
       'FRY2', 'FRY3', 'FRY4', 'FRY5', 'HR', 'HR0', 'HR02', 'HR03',
       'HR04', 'HR05', 'HR06', 'HU', 'HU1', 'HU11', 'HU12', 'HU2', 'HU21',
       'HU22', 'HU23', 'HU3', 'HU31', 'HU32', 'HU33', 'IE', 'IE0', 'IE04',
       'IE05', 'IE06', 'IS', 'IS0', 'IS00', 'IT', 'ITC', 'ITC1', 'ITC2',
       'ITC3', 'ITC4', 'ITF', 'ITF1', 'ITF2', 'ITF3', 'ITF4', 'ITF5',
       'ITF6', 'ITG', 'ITG1', 'ITG2', 'ITH', 'ITH1', 'ITH2', 'ITH3',
       'ITH4', 'ITH5', 'ITI', 'ITI1', 'ITI2', 'ITI3', 'ITI4', 'LI', 'LI0',
       'LI00', 'LT', 'LT0', 'LT01', 'LT02', 'LU', 'LU0', 'LU00', 'LV',
       'LV0', 'LV00', 'ME', 'ME0', 'ME00', 'MK', 'MK0', 'MK00', 'MT',
       'MT0', 'MT00', 'NL', 'NL1', 'NL11', 'NL12', 'NL13', 'NL2', 'NL21',
       'NL22', 'NL23', 'NL3', 'NL31', 'NL32', 'NL33', 'NL34', 'NL35',
       'NL36', 'NL4', 'NL41', 'NL42', 'NO', 'NO0', 'NO01', 'NO02', 'NO03',
       'NO04', 'NO05', 'NO06', 'NO07', 'NO08', 'NO09', 'NO0A', 'PL',
       'PL2', 'PL21', 'PL22', 'PL4', 'PL41', 'PL42', 'PL43', 'PL5',
       'PL51', 'PL52', 'PL6', 'PL61', 'PL62', 'PL63', 'PL7', 'PL71',
       'PL72', 'PL8', 'PL81', 'PL82', 'PL84', 'PL9', 'PL91', 'PL92', 'PT',
       'PT1', 'PT11', 'PT15', 'PT16', 'PT17', 'PT18', 'PT19', 'PT1A',
       'PT1B', 'PT1C', 'PT1D', 'PT2', 'PT20', 'PT3', 'PT30', 'RO', 'RO1',
       'RO11', 'RO12', 'RO2', 'RO21', 'RO22', 'RO3', 'RO31', 'RO32',
       'RO4', 'RO41', 'RO42', 'RS', 'RS1', 'RS11', 'RS12', 'RS2', 'RS21',
       'RS22', 'SE', 'SE1', 'SE11', 'SE12', 'SE2', 'SE21', 'SE22', 'SE23',
       'SE3', 'SE31', 'SE32', 'SE33', 'SI', 'SI0', 'SI03', 'SI04', 'SK',
       'SK0', 'SK01', 'SK02', 'SK03', 'SK04', 'TR', 'TR1', 'TR10', 'TR2',
       'TR21', 'TR22', 'TR3', 'TR31', 'TR32', 'TR33', 'TR4', 'TR41',
       'TR42', 'TR5', 'TR51', 'TR52', 'TR6', 'TR61', 'TR62', 'TR63',
       'TR7', 'TR71', 'TR72', 'TR8', 'TR81', 'TR82', 'TR83', 'TR9',
       'TR90', 'TRA', 'TRA1', 'TRA2', 'TRB', 'TRB1', 'TRB2', 'TRC',
       'TRC1', 'TRC2', 'TRC3', 'UK', 'UKC', 'UKC1', 'UKC2', 'UKD', 'UKD1',
       'UKD3', 'UKD4', 'UKD6', 'UKD7', 'UKE', 'UKE1', 'UKE2', 'UKE3',
       'UKE4', 'UKF', 'UKF1', 'UKF2', 'UKF3', 'UKG', 'UKG1', 'UKG2',
       'UKG3', 'UKH', 'UKH1', 'UKH2', 'UKH3', 'UKI', 'UKI3', 'UKI4',
       'UKI5', 'UKI6', 'UKI7', 'UKJ', 'UKJ1', 'UKJ2', 'UKJ3', 'UKJ4',
       'UKK', 'UKK1', 'UKK2', 'UKK3', 'UKK4', 'UKL', 'UKL1', 'UKL2',
       'UKM', 'UKM5', 'UKM6', 'UKM7', 'UKM8', 'UKM9', 'UKN', 'UKN0'],
      dtype=object)

In [11]:
df_life_exp_nuts2 = df_life_exp_clean[df_life_exp_clean['geo_time_period'].str.len() == 4]
df_life_exp_nuts2.geo_time_period.unique()

array(['AL01', 'AL02', 'AL03', 'AT11', 'AT12', 'AT13', 'AT21', 'AT22',
       'AT31', 'AT32', 'AT33', 'AT34', 'BE10', 'BE21', 'BE22', 'BE23',
       'BE24', 'BE25', 'BE31', 'BE32', 'BE33', 'BE34', 'BE35', 'BG31',
       'BG32', 'BG33', 'BG34', 'BG41', 'BG42', 'CH01', 'CH02', 'CH03',
       'CH04', 'CH05', 'CH06', 'CH07', 'CY00', 'CZ01', 'CZ02', 'CZ03',
       'CZ04', 'CZ05', 'CZ06', 'CZ07', 'CZ08', 'DE11', 'DE12', 'DE13',
       'DE14', 'DE21', 'DE22', 'DE23', 'DE24', 'DE25', 'DE26', 'DE27',
       'DE30', 'DE40', 'DE50', 'DE60', 'DE71', 'DE72', 'DE73', 'DE80',
       'DE91', 'DE92', 'DE93', 'DE94', 'DEA1', 'DEA2', 'DEA3', 'DEA4',
       'DEA5', 'DEB1', 'DEB2', 'DEB3', 'DEC0', 'DED2', 'DED4', 'DED5',
       'DEE0', 'DEF0', 'DEG0', 'DK01', 'DK02', 'DK03', 'DK04', 'DK05',
       'EE00', 'EL30', 'EL41', 'EL42', 'EL43', 'EL51', 'EL52', 'EL53',
       'EL54', 'EL61', 'EL62', 'EL63', 'EL64', 'EL65', 'ES11', 'ES12',
       'ES13', 'ES21', 'ES22', 'ES23', 'ES24', 'ES30', 'ES41', 'ES42',
       'ES43', 'ES51', 'ES52', 'ES53', 'ES61', 'ES62', 'ES63', 'ES64',
       'ES70', 'FI19', 'FI1B', 'FI1C', 'FI1D', 'FI20', 'FR10', 'FRB0',
       'FRC1', 'FRC2', 'FRD1', 'FRD2', 'FRE1', 'FRE2', 'FRF1', 'FRF2',
       'FRF3', 'FRG0', 'FRH0', 'FRI1', 'FRI2', 'FRI3', 'FRJ1', 'FRJ2',
       'FRK1', 'FRK2', 'FRL0', 'FRM0', 'FRY1', 'FRY2', 'FRY3', 'FRY4',
       'FRY5', 'HR02', 'HR03', 'HR04', 'HR05', 'HR06', 'HU11', 'HU12',
       'HU21', 'HU22', 'HU23', 'HU31', 'HU32', 'HU33', 'IE04', 'IE05',
       'IE06', 'IS00', 'ITC1', 'ITC2', 'ITC3', 'ITC4', 'ITF1', 'ITF2',
       'ITF3', 'ITF4', 'ITF5', 'ITF6', 'ITG1', 'ITG2', 'ITH1', 'ITH2',
       'ITH3', 'ITH4', 'ITH5', 'ITI1', 'ITI2', 'ITI3', 'ITI4', 'LI00',
       'LT01', 'LT02', 'LU00', 'LV00', 'ME00', 'MK00', 'MT00', 'NL11',
       'NL12', 'NL13', 'NL21', 'NL22', 'NL23', 'NL31', 'NL32', 'NL33',
       'NL34', 'NL35', 'NL36', 'NL41', 'NL42', 'NO01', 'NO02', 'NO03',
       'NO04', 'NO05', 'NO06', 'NO07', 'NO08', 'NO09', 'NO0A', 'PL21',
       'PL22', 'PL41', 'PL42', 'PL43', 'PL51', 'PL52', 'PL61', 'PL62',
       'PL63', 'PL71', 'PL72', 'PL81', 'PL82', 'PL84', 'PL91', 'PL92',
       'PT11', 'PT15', 'PT16', 'PT17', 'PT18', 'PT19', 'PT1A', 'PT1B',
       'PT1C', 'PT1D', 'PT20', 'PT30', 'RO11', 'RO12', 'RO21', 'RO22',
       'RO31', 'RO32', 'RO41', 'RO42', 'RS11', 'RS12', 'RS21', 'RS22',
       'SE11', 'SE12', 'SE21', 'SE22', 'SE23', 'SE31', 'SE32', 'SE33',
       'SI03', 'SI04', 'SK01', 'SK02', 'SK03', 'SK04', 'TR10', 'TR21',
       'TR22', 'TR31', 'TR32', 'TR33', 'TR41', 'TR42', 'TR51', 'TR52',
       'TR61', 'TR62', 'TR63', 'TR71', 'TR72', 'TR81', 'TR82', 'TR83',
       'TR90', 'TRA1', 'TRA2', 'TRB1', 'TRB2', 'TRC1', 'TRC2', 'TRC3',
       'UKC1', 'UKC2', 'UKD1', 'UKD3', 'UKD4', 'UKD6', 'UKD7', 'UKE1',
       'UKE2', 'UKE3', 'UKE4', 'UKF1', 'UKF2', 'UKF3', 'UKG1', 'UKG2',
       'UKG3', 'UKH1', 'UKH2', 'UKH3', 'UKI3', 'UKI4', 'UKI5', 'UKI6',
       'UKI7', 'UKJ1', 'UKJ2', 'UKJ3', 'UKJ4', 'UKK1', 'UKK2', 'UKK3',
       'UKK4', 'UKL1', 'UKL2', 'UKM5', 'UKM6', 'UKM7', 'UKM8', 'UKM9',
       'UKN0'], dtype=object)

In [12]:
def df_info(df):
    print("\n    ----- Shape -----")
    print(df.shape)
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    print("\n    ---- Statistics ---")
    return df.describe()
df_info(df_life_exp_nuts2)

    ----- Shape -----
(97770, 20)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
Index: 97770 entries, 2 to 144017
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   freq             97770 non-null  object
 1   unit             97770 non-null  object
 2   sex              97770 non-null  object
 3   age              97770 non-null  object
 4   geo_time_period  97770 non-null  object
 5   2010             77916 non-null  float64
 6   2011             78432 non-null  float64
 7   2012             77916 non-null  float64
 8   2013             81012 non-null  float64
 9   2014             93942 non-null  float64
 10  2015             93942 non-null  float64
 11  2016             94200 non-null  float64
 12  2017             95748 non-null  float64
 13  2018             95748 non-null  float64
 14  2019             86202 non-null  float64
 15  2020             78204 non-null  float64
 16  2021             77430 non-null  float64
 17  2022             76914 non-null  float64
 18  2023             82512 non-null  float64
 19  2024             76896 non-null  float64
dtypes: float64(15), object(5)
memory usage: 15.7+ MB
None

    ---- Empty Values ---
freq                   0
unit                   0
sex                    0
age                    0
geo_time_period        0
2010               19854
2011               19338
2012               19854
2013               16758
2014                3828
2015                3828
2016                3570
2017                2022
2018                2022
2019               11568
2020               19566
2021               20340
2022               20856
2023               15258
2024               20874
dtype: int64

    ----- Dtypes -----
freq                object
unit                object
sex                 object
age                 object
geo_time_period     object
2010               float64
2011               float64
2012               float64
2013               float64
2014               float64
2015               float64
2016               float64
2017               float64
2018               float64
2019               float64
2020               float64
2021               float64
2022               float64
2023               float64
2024               float64
dtype: object

    ---- Statistics ---

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
count,77916.000000,78432.000000,77916.000000,81012.000000,93942.000000,93942.000000,94200.00000,95748.000000,95748.000000,86202.000000,78204.000000,77430.000000,76914.000000,82512.000000,76896.000000
mean,40.040408,40.260053,40.274412,40.507554,37.527534,37.345961,37.59690,37.614976,37.714953,37.502234,36.626621,36.389739,36.741058,37.211710,37.356025
std,22.452091,22.489960,22.528573,22.555590,23.844772,23.847446,23.85755,23.866359,23.873242,24.016247,24.068072,24.020199,24.137102,24.086412,24.289622
min,4.000000,4.200000,3.700000,4.000000,1.400000,1.200000,1.00000,0.900000,0.700000,0.900000,0.800000,1.600000,1.300000,0.900000,1.400000
25%,19.700000,19.900000,19.900000,20.100000,15.600000,15.400000,15.70000,15.700000,15.800000,15.400000,14.300000,14.100000,14.400000,15.000000,14.900000
50%,38.600000,38.800000,38.900000,39.100000,35.500000,35.300000,35.60000,35.600000,35.700000,35.400000,34.400000,34.000000,34.500000,35.100000,35.200000
75%,59.400000,59.600000,59.700000,59.900000,58.100000,57.900000,58.20000,58.200000,58.300000,58.200000,57.400000,57.000000,57.600000,57.900000,58.300000
max,87.100000,87.000000,87.000000,87.600000,86.900000,86.500000,87.10000,86.900000,87.300000,87.400000,86.600000,87.300000,87.200000,88.300000,87.900000

In [13]:
df_life_exp_nuts2.to_csv('life_expect_nuts.csv', index=False, encoding='utf-8')