In [14]:
import pandas as pd
import eurostat

In [15]:
df_health = pd.read_csv(r"C:\Users\fotos\Desktop\Ironhack\Final_project\Final_project\data\raw\estat_hlth_cd_asdr2.tsv", sep="\t")
df_health.head()

,"freq,unit,sex,age,icd10,geo\TIME_PERIOD",2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,"A,RT,F,TOTAL,A-R_V-Y,AT",:,:,:,:,:,:,:,784.67,765.68,819.09,807.4,:,:
1,"A,RT,F,TOTAL,A-R_V-Y,AT1",:,:,:,:,:,:,:,836.28,799.23,845.58,859.88,:,:
2,"A,RT,F,TOTAL,A-R_V-Y,AT11",:,:,:,:,:,:,:,814.31,800.48,856.48,830.61,:,:
3,"A,RT,F,TOTAL,A-R_V-Y,AT12",:,:,:,:,:,:,:,831.56,810.46,835.14,871.85,:,:
4,"A,RT,F,TOTAL,A-R_V-Y,AT13",:,:,:,:,:,:,:,842.79,784.87,851.54,851.16,:,:

In [16]:
table_code = 'hlth_cd_asdr2'
df_mortalidad = eurostat.get_data_df(table_code)
display(df_mortalidad.head())

,freq,unit,sex,age,icd10,geo\TIME_PERIOD,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,A,RT,F,TOTAL,A-R_V-Y,AT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,784.67,765.68,819.09,807.40,NaN,NaN
1,A,RT,F,TOTAL,A-R_V-Y,AT1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,836.28,799.23,845.58,859.88,NaN,NaN
2,A,RT,F,TOTAL,A-R_V-Y,AT11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,814.31,800.48,856.48,830.61,NaN,NaN
3,A,RT,F,TOTAL,A-R_V-Y,AT12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,831.56,810.46,835.14,871.85,NaN,NaN
4,A,RT,F,TOTAL,A-R_V-Y,AT13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,842.79,784.87,851.54,851.16,NaN,NaN

In [17]:
df_mortalidad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406323 entries, 0 to 406322
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   freq             406323 non-null  object
 1   unit             406323 non-null  object
 2   sex              406323 non-null  object
 3   age              406323 non-null  object
 4   icd10            406323 non-null  object
 5   geo\TIME_PERIOD  406323 non-null  object
 6   2011             342960 non-null  float64
 7   2012             343137 non-null  float64
 8   2013             363822 non-null  float64
 9   2014             365124 non-null  float64
 10  2015             365250 non-null  float64
 11  2016             365226 non-null  float64
 12  2017             364890 non-null  float64
 13  2018             364779 non-null  float64
 14  2019             323682 non-null  float64
 15  2020             336147 non-null  float64
 16  2021             336078 non-null  float64
 17  2022             333489 non-null  float64
 18  2023             339104 non-null  float64
dtypes: float64(13), object(6)
memory usage: 58.9+ MB

In [18]:
df_mortalidad.rename(columns={col : col.strip() for col in df_mortalidad.columns}, inplace = True)
df_mortalidad.rename(columns={col : col.replace("\\", "_").lower() for col in df_mortalidad.columns}, inplace = True)

In [19]:
df_mortalidad.shape

(406323, 19)

In [20]:
df_mortalidad.dtypes

freq                object
unit                object
sex                 object
age                 object
icd10               object
geo_time_period     object
2011               float64
2012               float64
2013               float64
2014               float64
2015               float64
2016               float64
2017               float64
2018               float64
2019               float64
2020               float64
2021               float64
2022               float64
2023               float64
dtype: object

In [21]:
df_mortalidad.freq.unique()

array(['A'], dtype=object)

In [22]:
df_mortalidad.unit.unique()

array(['RT'], dtype=object)

In [23]:
df_mortalidad.age.unique()

array(['TOTAL', 'Y_GE65', 'Y_LT65'], dtype=object)

In [24]:
df_mortalidad.icd10.unique()

array(['A-R_V-Y', 'A15-A19_B90', 'ACC', 'ACC_OTH', 'A_B', 'A_B_OTH',
       'B15-B19_B942', 'B180-B182', 'B20-B24', 'C', 'C00-C14', 'C00-D48',
       'C15', 'C16', 'C18-C21', 'C22', 'C25', 'C32', 'C33_C34', 'C43',
       'C50', 'C53', 'C54_C55', 'C56', 'C61', 'C64', 'C67', 'C70-C72',
       'C73', 'C81-C86', 'C88_C90_C96', 'C91-C95', 'C_OTH', 'D00-D48',
       'D50-D89', 'E', 'E10-E14', 'E_OTH', 'F', 'F01_F03', 'F10', 'F_OTH',
       'G20', 'G30', 'G_H', 'G_H_OTH', 'I', 'I20-I25', 'I20_I23-I25',
       'I21_I22', 'I30-I51', 'I60-I69', 'I_OTH', 'J', 'J09-J11',
       'J12-J18', 'J40-J44_J47', 'J40-J47', 'J45_J46', 'J_OTH', 'K',
       'K25-K28', 'K70_K73_K74', 'K72-K75', 'K_OTH', 'L', 'M', 'M_OTH',
       'N', 'N00-N29', 'N_OTH', 'O', 'P', 'Q', 'R', 'R95', 'R96-R99',
       'RHEUM_ARTHRO', 'R_OTH', 'TOTAL', 'TOXICO', 'U071', 'U072',
       'U_COV19_OTH', 'V01-Y89', 'V01-Y89_OTH', 'V_Y85', 'W00-W19',
       'W65-W74', 'X40-X49', 'X60-X84_Y870', 'X85-Y09_Y871',
       'Y10-Y34_Y872'], dtype=object)

In [45]:
#Standardised Death Rate or ASDR - number of death for every 100,000 habitants

# 🎯 Relevant Codes for Air & Water Pollution

## 🌬️ Air Pollution Related
These codes are highly linked to particulate matter ($PM_{2.5}$, $PM_{10}$), nitrogen dioxide ($NO_2$), ozone ($O_3$), and industrial emissions.

* **`C33_C34`**: Malignant neoplasms of trachea, bronchus, and lung (Lung cancer strongly tied to air quality).
* **`I`**: Diseases of the circulatory system (Broad category; air pollution is a major driver of cardiovascular mortality).
    * **`I20-I25`** / **`I20_I23-I25`**: Ischemic heart diseases.
    * **`I21_I22`**: Acute myocardial infarction (Heart attacks triggered by acute pollution spikes).
    * **`I60-I69`**: Cerebrovascular diseases (Stroke risks increase with heavy air pollution).
* **`J`**: Diseases of the respiratory system (The most directly impacted system).
    * **`J40-Y44_J47`** / **`J40-Subject_47`**: Chronic lower respiratory diseases (COPD, emphysema).
    * **`J45_J46`**: Asthma and status asthmaticus (Exacerbated heavily by poor air quality).

---

## 💧 Water Pollution & Environmental Toxins Related
These codes relate to waterborne pathogens, heavy metals (lead, arsenic, cadmium), chemical runoff, or direct accidental ingestion of toxins.

* **`A_B`**: Certain infectious and parasitic diseases (Includes waterborne diarrheal diseases, cholera, and gastrointestinal infections).
* **`B15-B19_B942`**: Viral hepatitis (Hepatitis A and E are primarily transmitted through contaminated water).
* **`N00-N29`**: Diseases of the genitourinary system / Renal failure (Kidneys are highly sensitive to heavy metals like lead, cadmium, and mercury found in polluted water).
* **`TOXICO`**: Toxicological effects / Poisoning.
* **`X40-X49`**: Accidental poisoning by and exposure to noxious substances (Includes pesticide runoff or chemical spills in water resources).

In [25]:
df_mortalidad.geo_time_period.unique()

array(['AT', 'AT1', 'AT11', 'AT12', 'AT13', 'AT2', 'AT21', 'AT22', 'AT3',
       'AT31', 'AT32', 'AT33', 'AT34', 'BE', 'BE1', 'BE10', 'BE2', 'BE21',
       'BE22', 'BE23', 'BE24', 'BE25', 'BE3', 'BE31', 'BE32', 'BE33',
       'BE34', 'BE35', 'BG', 'BG3', 'BG31', 'BG32', 'BG33', 'BG34', 'BG4',
       'BG41', 'BG42', 'CH', 'CH0', 'CH01', 'CH02', 'CH03', 'CH04',
       'CH05', 'CH06', 'CH07', 'CY', 'CY0', 'CY00', 'CZ', 'CZ0', 'CZ01',
       'CZ02', 'CZ03', 'CZ04', 'CZ05', 'CZ06', 'CZ07', 'CZ08', 'DE',
       'DE1', 'DE11', 'DE12', 'DE13', 'DE14', 'DE2', 'DE21', 'DE22',
       'DE23', 'DE24', 'DE25', 'DE26', 'DE27', 'DE3', 'DE30', 'DE4',
       'DE40', 'DE5', 'DE50', 'DE6', 'DE60', 'DE7', 'DE71', 'DE72',
       'DE73', 'DE8', 'DE80', 'DE9', 'DE91', 'DE92', 'DE93', 'DE94',
       'DEA', 'DEA1', 'DEA2', 'DEA3', 'DEA4', 'DEA5', 'DEB', 'DEB1',
       'DEB2', 'DEB3', 'DEC', 'DEC0', 'DED', 'DED2', 'DED4', 'DED5',
       'DEE', 'DEE0', 'DEF', 'DEF0', 'DEG', 'DEG0', 'DK', 'DK0', 'DK01',
       'DK02', 'DK03', 'DK04', 'DK05', 'EE', 'EE0', 'EE00', 'EL', 'EL3',
       'EL30', 'EL4', 'EL41', 'EL42', 'EL43', 'EL5', 'EL51', 'EL52',
       'EL53', 'EL54', 'EL6', 'EL61', 'EL62', 'EL63', 'EL64', 'EL65',
       'ES', 'ES1', 'ES11', 'ES12', 'ES13', 'ES2', 'ES21', 'ES22', 'ES23',
       'ES24', 'ES3', 'ES30', 'ES4', 'ES41', 'ES42', 'ES43', 'ES5',
       'ES51', 'ES52', 'ES53', 'ES6', 'ES61', 'ES62', 'ES63', 'ES64',
       'ES7', 'ES70', 'EU27_2020', 'FI', 'FI1', 'FI19', 'FI1B', 'FI1C',
       'FI1D', 'FI2', 'FI20', 'FR', 'FR1', 'FR10', 'FRB', 'FRB0', 'FRC',
       'FRC1', 'FRC2', 'FRD', 'FRD1', 'FRD2', 'FRE', 'FRE1', 'FRE2',
       'FRF', 'FRF1', 'FRF2', 'FRF3', 'FRG', 'FRG0', 'FRH', 'FRH0', 'FRI',
       'FRI1', 'FRI2', 'FRI3', 'FRJ', 'FRJ1', 'FRJ2', 'FRK', 'FRK1',
       'FRK2', 'FRL', 'FRL0', 'FRM', 'FRM0', 'FRY', 'FRY1', 'FRY2',
       'FRY3', 'FRY4', 'FRY5', 'HR', 'HR0', 'HR02', 'HR03', 'HR04',
       'HR05', 'HR06', 'HU', 'HU1', 'HU11', 'HU12', 'HU2', 'HU21', 'HU22',
       'HU23', 'HU3', 'HU31', 'HU32', 'HU33', 'IE', 'IE0', 'IE04', 'IE05',
       'IE06', 'IS', 'IS0', 'IS00', 'IT', 'ITC', 'ITC1', 'ITC2', 'ITC3',
       'ITC4', 'ITF', 'ITF1', 'ITF2', 'ITF3', 'ITF4', 'ITF5', 'ITF6',
       'ITG', 'ITG1', 'ITG2', 'ITH', 'ITH1', 'ITH2', 'ITH3', 'ITH4',
       'ITH5', 'ITI', 'ITI1', 'ITI2', 'ITI3', 'ITI4', 'LI', 'LI0', 'LI00',
       'LT', 'LT0', 'LT01', 'LT02', 'LU', 'LU0', 'LU00', 'LV', 'LV0',
       'LV00', 'MT', 'MT0', 'MT00', 'NL', 'NL1', 'NL11', 'NL12', 'NL13',
       'NL2', 'NL21', 'NL22', 'NL23', 'NL3', 'NL31', 'NL32', 'NL33',
       'NL34', 'NL4', 'NL41', 'NL42', 'NO', 'NO0', 'NO01', 'NO02', 'NO03',
       'NO04', 'NO05', 'NO06', 'NO07', 'NO08', 'NO09', 'NO0A', 'PL',
       'PL2', 'PL21', 'PL22', 'PL4', 'PL41', 'PL42', 'PL43', 'PL5',
       'PL51', 'PL52', 'PL6', 'PL61', 'PL62', 'PL63', 'PL7', 'PL71',
       'PL72', 'PL8', 'PL81', 'PL82', 'PL84', 'PL9', 'PL91', 'PL92', 'PT',
       'PT1', 'PT11', 'PT15', 'PT16', 'PT17', 'PT18', 'PT2', 'PT20',
       'PT3', 'PT30', 'RO', 'RO1', 'RO11', 'RO12', 'RO2', 'RO21', 'RO22',
       'RO3', 'RO31', 'RO32', 'RO4', 'RO41', 'RO42', 'RS', 'RS1', 'RS11',
       'RS12', 'RS2', 'RS21', 'RS22', 'SE', 'SE1', 'SE11', 'SE12', 'SE2',
       'SE21', 'SE22', 'SE23', 'SE3', 'SE31', 'SE32', 'SE33', 'SI', 'SI0',
       'SI03', 'SI04', 'SK', 'SK0', 'SK01', 'SK02', 'SK03', 'SK04', 'TR',
       'TR1', 'TR10', 'TR2', 'TR21', 'TR22', 'TR3', 'TR31', 'TR32',
       'TR33', 'TR4', 'TR41', 'TR42', 'TR5', 'TR51', 'TR52', 'TR6',
       'TR61', 'TR62', 'TR63', 'TR7', 'TR71', 'TR72', 'TR8', 'TR81',
       'TR82', 'TR83', 'TR9', 'TR90', 'TRA', 'TRA1', 'TRA2', 'TRB',
       'TRB1', 'TRB2', 'TRC', 'TRC1', 'TRC2', 'TRC3', 'UK', 'UKC', 'UKC1',
       'UKC2', 'UKD', 'UKD1', 'UKD3', 'UKD4', 'UKD6', 'UKD7', 'UKE',
       'UKE1', 'UKE2', 'UKE3', 'UKE4', 'UKF', 'UKF1', 'UKF2', 'UKF3',
       'UKG', 'UKG1', 'UKG2', 'UKG3', 'UKH', 'UKH1', 'UKH2', 'UKH3',
       'UKI', 'UKI3', 'UKI4', 'UKI5', 'UKI6', 'UKI7', 'UKJ', 'UKJ1',
       'UKJ2', 'UKJ3', 'UKJ4', 'UKK', 'UKK1', 'UKK2', 'UKK3', 'UKK4',
       'UKL', 'UKL1', 'UKL2', 'UKM', 'UKM5', 'UKM6', 'UKM7', 'UKM8',
       'UKM9', 'UKN', 'UKN0', 'EU28', 'GE', 'MD', 'NL36', 'PT19', 'PT1A',
       'PT1B', 'PT1C', 'PT1D', 'NL35'], dtype=object)

In [35]:
df_mortality_nuts2.head()

,freq,unit,sex,age,icd10,geo_time_period,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
2,A,RT,F,TOTAL,A-R_V-Y,AT11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,814.31,800.48,856.48,830.61,NaN,NaN
3,A,RT,F,TOTAL,A-R_V-Y,AT12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,831.56,810.46,835.14,871.85,NaN,NaN
4,A,RT,F,TOTAL,A-R_V-Y,AT13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,842.79,784.87,851.54,851.16,NaN,NaN
6,A,RT,F,TOTAL,A-R_V-Y,AT21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,775.94,740.61,810.73,765.47,NaN,NaN
7,A,RT,F,TOTAL,A-R_V-Y,AT22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,757.61,747.26,836.57,771.05,NaN,NaN

In [27]:
df_mortality_nuts2 = df_mortalidad[df_mortalidad['geo_time_period'].str.len() == 4]
df_mortality_nuts2.geo_time_period.unique()

array(['AT11', 'AT12', 'AT13', 'AT21', 'AT22', 'AT31', 'AT32', 'AT33',
       'AT34', 'BE10', 'BE21', 'BE22', 'BE23', 'BE24', 'BE25', 'BE31',
       'BE32', 'BE33', 'BE34', 'BE35', 'BG31', 'BG32', 'BG33', 'BG34',
       'BG41', 'BG42', 'CH01', 'CH02', 'CH03', 'CH04', 'CH05', 'CH06',
       'CH07', 'CY00', 'CZ01', 'CZ02', 'CZ03', 'CZ04', 'CZ05', 'CZ06',
       'CZ07', 'CZ08', 'DE11', 'DE12', 'DE13', 'DE14', 'DE21', 'DE22',
       'DE23', 'DE24', 'DE25', 'DE26', 'DE27', 'DE30', 'DE40', 'DE50',
       'DE60', 'DE71', 'DE72', 'DE73', 'DE80', 'DE91', 'DE92', 'DE93',
       'DE94', 'DEA1', 'DEA2', 'DEA3', 'DEA4', 'DEA5', 'DEB1', 'DEB2',
       'DEB3', 'DEC0', 'DED2', 'DED4', 'DED5', 'DEE0', 'DEF0', 'DEG0',
       'DK01', 'DK02', 'DK03', 'DK04', 'DK05', 'EE00', 'EL30', 'EL41',
       'EL42', 'EL43', 'EL51', 'EL52', 'EL53', 'EL54', 'EL61', 'EL62',
       'EL63', 'EL64', 'EL65', 'ES11', 'ES12', 'ES13', 'ES21', 'ES22',
       'ES23', 'ES24', 'ES30', 'ES41', 'ES42', 'ES43', 'ES51', 'ES52',
       'ES53', 'ES61', 'ES62', 'ES63', 'ES64', 'ES70', 'FI19', 'FI1B',
       'FI1C', 'FI1D', 'FI20', 'FR10', 'FRB0', 'FRC1', 'FRC2', 'FRD1',
       'FRD2', 'FRE1', 'FRE2', 'FRF1', 'FRF2', 'FRF3', 'FRG0', 'FRH0',
       'FRI1', 'FRI2', 'FRI3', 'FRJ1', 'FRJ2', 'FRK1', 'FRK2', 'FRL0',
       'FRM0', 'FRY1', 'FRY2', 'FRY3', 'FRY4', 'FRY5', 'HR02', 'HR03',
       'HR04', 'HR05', 'HR06', 'HU11', 'HU12', 'HU21', 'HU22', 'HU23',
       'HU31', 'HU32', 'HU33', 'IE04', 'IE05', 'IE06', 'IS00', 'ITC1',
       'ITC2', 'ITC3', 'ITC4', 'ITF1', 'ITF2', 'ITF3', 'ITF4', 'ITF5',
       'ITF6', 'ITG1', 'ITG2', 'ITH1', 'ITH2', 'ITH3', 'ITH4', 'ITH5',
       'ITI1', 'ITI2', 'ITI3', 'ITI4', 'LI00', 'LT01', 'LT02', 'LU00',
       'LV00', 'MT00', 'NL11', 'NL12', 'NL13', 'NL21', 'NL22', 'NL23',
       'NL31', 'NL32', 'NL33', 'NL34', 'NL41', 'NL42', 'NO01', 'NO02',
       'NO03', 'NO04', 'NO05', 'NO06', 'NO07', 'NO08', 'NO09', 'NO0A',
       'PL21', 'PL22', 'PL41', 'PL42', 'PL43', 'PL51', 'PL52', 'PL61',
       'PL62', 'PL63', 'PL71', 'PL72', 'PL81', 'PL82', 'PL84', 'PL91',
       'PL92', 'PT11', 'PT15', 'PT16', 'PT17', 'PT18', 'PT20', 'PT30',
       'RO11', 'RO12', 'RO21', 'RO22', 'RO31', 'RO32', 'RO41', 'RO42',
       'RS11', 'RS12', 'RS21', 'RS22', 'SE11', 'SE12', 'SE21', 'SE22',
       'SE23', 'SE31', 'SE32', 'SE33', 'SI03', 'SI04', 'SK01', 'SK02',
       'SK03', 'SK04', 'TR10', 'TR21', 'TR22', 'TR31', 'TR32', 'TR33',
       'TR41', 'TR42', 'TR51', 'TR52', 'TR61', 'TR62', 'TR63', 'TR71',
       'TR72', 'TR81', 'TR82', 'TR83', 'TR90', 'TRA1', 'TRA2', 'TRB1',
       'TRB2', 'TRC1', 'TRC2', 'TRC3', 'UKC1', 'UKC2', 'UKD1', 'UKD3',
       'UKD4', 'UKD6', 'UKD7', 'UKE1', 'UKE2', 'UKE3', 'UKE4', 'UKF1',
       'UKF2', 'UKF3', 'UKG1', 'UKG2', 'UKG3', 'UKH1', 'UKH2', 'UKH3',
       'UKI3', 'UKI4', 'UKI5', 'UKI6', 'UKI7', 'UKJ1', 'UKJ2', 'UKJ3',
       'UKJ4', 'UKK1', 'UKK2', 'UKK3', 'UKK4', 'UKL1', 'UKL2', 'UKM5',
       'UKM6', 'UKM7', 'UKM8', 'UKM9', 'UKN0', 'EU28', 'NL36', 'PT19',
       'PT1A', 'PT1B', 'PT1C', 'PT1D', 'NL35'], dtype=object)

In [37]:
df_mortality_nuts2.head()

,freq,unit,sex,age,icd10,geo_time_period,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
2,A,RT,F,TOTAL,A-R_V-Y,AT11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,814.31,800.48,856.48,830.61,NaN,NaN
3,A,RT,F,TOTAL,A-R_V-Y,AT12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,831.56,810.46,835.14,871.85,NaN,NaN
4,A,RT,F,TOTAL,A-R_V-Y,AT13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,842.79,784.87,851.54,851.16,NaN,NaN
6,A,RT,F,TOTAL,A-R_V-Y,AT21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,775.94,740.61,810.73,765.47,NaN,NaN
7,A,RT,F,TOTAL,A-R_V-Y,AT22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,757.61,747.26,836.57,771.05,NaN,NaN

In [28]:
df_mortality_nuts2.dtypes

freq                object
unit                object
sex                 object
age                 object
icd10               object
geo_time_period     object
2011               float64
2012               float64
2013               float64
2014               float64
2015               float64
2016               float64
2017               float64
2018               float64
2019               float64
2020               float64
2021               float64
2022               float64
2023               float64
dtype: object

In [29]:
#df_mortality_nuts2_clean = df_mortality_nuts2.dropna()

In [39]:
#df_mortality_nuts2_clean.head()

In [30]:
df_mortality_nuts2.shape

(276177, 19)

In [31]:
df_mortality_nuts2_clean.shape

(172335, 19)

In [46]:
relevant_diseases = [
    # Air Pollution Related
    "C33_C34", "I", "I20-I25", "I20_I23-I25", "I21_I22", "I60-I69", 
    "J", "J40-J44_J47", "J40-J47", "J45_J46",
    # Water Pollution Related
    "A_B", "B15-B19_B942", "N00-N29", "TOXICO", "X40-X49"
]

df_mortality_nuts2_clean = df_mortality_nuts2_clean[df_mortality_nuts2_clean['icd10'].isin(relevant_diseases)]
df_mortality_nuts2_clean.shape

(30462, 19)

In [52]:
df_mortality_nuts2_clean.to_csv('sickness_nuts_clean.csv', index=False, encoding='utf-8')

In [48]:
df_mortality_nuts2_clean.sex.unique()

array(['F', 'M', 'T'], dtype=object)

In [38]:
#df_mortality_nuts2_clean.head()

In [49]:
(df_mortality_nuts2_clean.isna().mean() * 100).round(2)

freq               0.0
unit               0.0
sex                0.0
age                0.0
icd10              0.0
geo_time_period    0.0
2011               0.0
2012               0.0
2013               0.0
2014               0.0
2015               0.0
2016               0.0
2017               0.0
2018               0.0
2019               0.0
2020               0.0
2021               0.0
2022               0.0
2023               0.0
dtype: float64

In [50]:
#df_mortality_nuts2_clean.dropna()

In [42]:
df_mortality_nuts2.iloc[493]

freq                         A
unit                        RT
sex                          F
age                      TOTAL
icd10              A15-A19_B90
geo_time_period           HU23
2011                      0.36
2012                      1.02
2013                      0.35
2014                      0.33
2015                      0.19
2016                       NaN
2017                       0.2
2018                      0.35
2019                      0.42
2020                      0.31
2021                      0.16
2022                       0.5
2023                      0.33
Name: 726, dtype: object

In [44]:
df_mortality_nuts2_clean.iloc[0]

freq                         A
unit                        RT
sex                          F
age                      TOTAL
icd10              A15-A19_B90
geo_time_period           AT12
2011                      0.33
2012                      0.51
2013                      0.36
2014                      0.54
2015                      0.27
2016                       0.1
2017                      0.37
2018                      0.48
2019                      0.08
2020                      0.39
2021                      0.22
2022                      0.44
2023                      0.48
Name: 493, dtype: object

In [51]:
df_mortality_nuts2_clean.head()

,freq,unit,sex,age,icd10,geo_time_period,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
1989,A,RT,F,TOTAL,A_B,AT11,6.95,3.07,6.36,6.24,5.96,5.72,5.03,8.84,5.19,7.14,4.74,6.11,7.53
1990,A,RT,F,TOTAL,A_B,AT12,4.96,6.03,6.71,6.68,5.21,8.01,7.13,8.99,10.93,8.53,10.03,8.76,12.56
1991,A,RT,F,TOTAL,A_B,AT13,9.67,10.12,10.01,8.45,9.80,9.51,9.97,11.89,10.81,8.83,9.34,8.05,10.47
1993,A,RT,F,TOTAL,A_B,AT21,5.93,7.19,5.50,7.84,6.55,9.59,10.98,10.45,9.96,7.30,8.79,5.63,12.13
1994,A,RT,F,TOTAL,A_B,AT22,6.05,6.32,6.14,5.19,9.25,7.19,8.37,8.64,8.13,9.47,8.15,6.25,7.69

In [53]:
df_mortality_nuts2_long = pd.melt(
    df_mortality_nuts2_clean,
    id_vars=['freq', 'unit', 'sex', 'age', 'icd10', 'geo_time_period'], 
    var_name='year',                                               
    value_name='mortality_rate'                                
)
df_mortality_nuts2_long.head()

  freq unit sex    age icd10 geo_time_period  year  mortality_rate
0    A   RT   F  TOTAL   A_B            AT11  2011            6.95
1    A   RT   F  TOTAL   A_B            AT12  2011            4.96
2    A   RT   F  TOTAL   A_B            AT13  2011            9.67
3    A   RT   F  TOTAL   A_B            AT21  2011            5.93
4    A   RT   F  TOTAL   A_B            AT22  2011            6.05

In [55]:
df_mortality_nuts2_long.to_csv('df_mortality_nuts2_long.csv', index=False, encoding='utf-8', sep=";")